### ISSUE TITLE
v0.8 implementation report

### ISSUE THREAD

**Issue by sbrl** [ohwgiles/laminar#107]
Not an issue per-se, but thought I'd detail my upgrade experience to v0.8 for you :-)

 - Upgrading itself was mostly smooth - though I did run into an issue whereby the upgrade replaced my systemd service file and I had to rewrite my modifications to it (I'm using a unix socket on  disk with custom permissions). I've now moved those permissions to use `systemctl edit laminar`, so this hopefully shouldn't cause any more issues.
 - The new contexts system is so much  easier to use in practice! Thanks so much :D
 - I had to tweak my config obviously, but it's all going like clockwork now :D
 - The web interface takes longer with the "connecting" spinner now than it used to.
 - I've just finished a [6 part series on my blog](https://starbeamrainbowlabs.com/blog/article.php?article=posts/392-own-your-code-series-list.html) on my Gitea + Laminar CI setup. I've put a significant amount of work into it, so I'm pretty sure I'll be keeping it for the foreseeable future.

**Comment by ohwgiles** [comment]
Hey, thanks for sharing your experiences, I’m glad to hear version 0.8 is working well for you.

And very detailed write-up, nice one :)
