### ISSUE TITLE
Empty console output under /jobs/X/Y

### ISSUE THREAD

**Issue by tsieprawski** [ohwgiles/laminar#111]
Today I've built laminar from commit f981491a34f744e4c85aba9b2d692d0081d4d865 and noticed that when going into `/jobs/X/Y` `Console output` section stays empty. `/log/X/Y` does contains the logs. I get this for however much I run the job. :(

![2020-02-26-161539_881x545_scrot](https://user-images.githubusercontent.com/12021749/75358694-9aef8480-58b3-11ea-91af-4c01f93df730.png)
![2020-02-26-161531_891x546_scrot](https://user-images.githubusercontent.com/12021749/75358696-9c20b180-58b3-11ea-8b79-7f6caf5a526b.png)

**Comment by ohwgiles** [comment]
That is troubling! That’s Firefox, right? Which version? Can you check the JavaScript console for errors?

**Comment by tsieprawski** [comment]
Actually I haven't thought that it can be because of the browser. Sure, but first I'll compare firefox with chrome.

**Comment by tsieprawski** [comment]
I had outdated Firefox. I've just `apt update && apt install firefox-esr`-ed from 60.9.0 to debian testing's 68.5.0 and everything works fine.
Thanks anyway for your support. :) 

![image](https://user-images.githubusercontent.com/12021749/75377757-c0d85180-58d2-11ea-86d0-6175100f3419.png)
