### ISSUE TITLE
Extra links in the menu bar

### ISSUE THREAD

**Issue by cweagans** [ohwgiles/laminar#112]
It'd be awesome to be able to add extra links in the menu bar, either via a config option or overriding the template somehow. I have two things that I'd want to put there: one is a logout link  (I'm running Laminar behind a proxy that requires authentication, and I'm required to have a logout button there -- it'll point to a static location, so no need to add fancy params or anything) and another is an administrative interface where users will be able to kick off jobs with specific params. Since Laminar doesn't support a build now button, I at least need to be able to link to the interface that I built that supports it. I could do this from the description of each related job, but that's pretty cumbersome compared to a link in the menu bar.

Is this a possibility?

**Comment by ohwgiles** [comment]
I've been thinking about this for a while, but haven't come up with a great solution. Page templates are statically compiled into the application, there's no server-side processing of them at all; the server sends structured JSON over websocket to populate all data. This is great for the job data, but not so suitable for static links which never change. So far I made an exception for the page title, and that's all. Alternatively there's the custom css option, but you need a little more than that for what you want here.

Definitely a possibility, implementation needs some thought.

**Comment by ohwgiles** [comment]
In the meantime, I'd recommend just hacking it in yourself and rebuilding Laminar locally. It's a tiny, simple hand-written html file, and for the sake of two lines of `<a>` maybe it's not worth the hassle

**Comment by cweagans** [comment]
In working through the webui design refresh, I think I've got a decent way to handle this. I'm thinking that I can serve up a custom index.html if it's present, and if not, fall back to the copy that's packaged into the binary. This would make it possible for people to completely re-theme Laminar on their own if they wanted to as well (although, that's very much a secondary goal at this point).

Do you have any objection to that approach? If not, I'll tackle it tomorrow.

**Comment by cweagans** [comment]
PR is open ^^
