### ISSUE TITLE
laminarc set fails when executed inside a job

### ISSUE THREAD

**Issue by rerobins** [ohwgiles/laminar#118]
When I execute a script an execute `env` in the bash script, the `__LAMINAR_SETENV_PIPE` variable is not defined.  This causes the set command to exit with an error.

```
+ laminarc set PROJECT_DIRECTORY=accounts
Must be run from within a laminar job
```
Here is the output of my env command:

```
SHELL=/bin/bash
PWD=/usr/local/data/laminar/run/accounts_update/443
LOGNAME=laminar
HOME=/usr/local/data/laminar
LANG=en_US.UTF-8
LAMINAR_HOME=/usr/local/data/laminar
JOB=accounts_update
INVOCATION_ID=31cff31517ab4334b5de91a493f33d3d
RUN=443
WORKSPACE=/usr/local/data/laminar/run/accounts_update/workspace
ARCHIVE=/usr/local/data/laminar/archive/accounts_update/443
RESULT=success
LAST_RESULT=failed
USER=laminar
SHLVL=1
JOURNAL_STREAM=8:413177
PATH=/usr/local/data/laminar/cfg/scripts:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
_=/usr/bin/env
```

This issue is new in 0.8

**Comment by rerobins** [comment]
Figured it out.  Was running the old version of laminard.  My `/etc/systemd/system/laminar.service` file was still pointing to the laminard that was in `/usr/bin/` and not `/usr/sbin`.

Is there a way to determine the version of laminard that is running by looking at the web page?  Was also looking for a version in the laminarc executable as well.

**Comment by ohwgiles** [comment]
Glad you figured it out. Displaying the version on the webpage and in laminarc sounds like a good idea, feel free to post a PR or open a dedicated issue and I’ll get to it sometime
