### ISSUE TITLE
Running bash over ssh with different results from local and remote run

### ISSUE THREAD

**Issue by palica** [ohwgiles/laminar#12]
I am trying to execute a script over ssh, but get different results when compared to starting a local script.

## Executing a script on the remote machine:
This is the pkg-builder-remote.run file on laminar server
```
#!/bin/bash
echo Running on robor ...
ssh root@10.214.101.1 /bin/bash /root/test.sh
echo Done
```
And this is the test.sh file on the remote server:
```
#!/bin/bash
C_NAME=pkg-builder-1
echo $C_NAME
lxc launch -e -p prf-funtoo -p default fun-generic "$C_NAME"
sleep 3
lxc exec "$C_NAME" ip a add 10.214.101.2/24 dev eth0
lxc exec "$C_NAME" -- ping -c3 10.214.101.1
echo "Waiting 3 seconds"
sleep 3
lxc exec "$C_NAME" -- poweroff
```
Results from the run as displayed on laminar:
pkg-builder-remote #1

```
Console output

[laminar] Executing /var/lib/laminar/cfg/jobs/pkg-builder-remote.run
Running on robor ...
pkg-builder-1
Creating pkg-builder-1


Starting pkg-builder-1
PING 10.214.101.1 (10.214.101.1) 56(84) bytes of data.
64 bytes from 10.214.101.1: icmp_seq=1 ttl=64 time=0.152 ms
64 bytes from 10.214.101.1: icmp_seq=2 ttl=64 time=0.056 ms
64 bytes from 10.214.101.1: icmp_seq=3 ttl=64 time=0.054 ms

--- 10.214.101.1 ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2118ms
rtt min/avg/max/mdev = 0.054/0.087/0.152/0.046 ms
Waiting 3 seconds
Done

```

## Executing the script over ssh connection
This is the pkg-builder.run file on laminar server:

```
#!/bin/bash
C_NAME=pkg-builder-$RUN

echo Connecting to remote host and starting container $C_NAME
ssh root@10.214.101.1 "env C_NAME=$C_NAME /bin/bash -xe"<<"EOF"
        echo $C_NAME
        lxc launch -e -p prf-funtoo -p default fun-generic "$C_NAME"
        sleep 3
        lxc exec "$C_NAME" ip a add 10.214.101.2/24 dev eth0
        lxc exec "$C_NAME" -- ping -c3 10.214.101.1
        echo "Waiting 3 seconds"
        sleep 3
        lxc exec "$C_NAME" -- poweroff
EOF
```

This is the output from laminar:
```
Console output

[laminar] Executing /var/lib/laminar/cfg/jobs/pkg-builder.run
We are going to start container:
Connecting to remote host and starting container pkg-builder-37
+ lxc launch -e -p prf-funtoo -p default fun-generic pkg-builder-37
Creating pkg-builder-37


Starting pkg-builder-37
+ sleep 3
+ lxc exec pkg-builder-37 ip a add 10.214.101.2/24 dev eth0

```
So the ping command and sleep and poweroff commands never get executed.

Am I doing something wrong?

Thanks

**Comment by ohwgiles** [comment]
The difference is, `test.sh` on the remote server has the shebang `#!/bin/bash`, while this line on laminar

> `ssh root@10.214.101.1 "env C_NAME=$C_NAME /bin/bash -xe"<<"EOF"`

executes under `/bin/bash -xe`. `-x` causes each line to be printed before its executed (that's what causes all the lines beginning with `+`), and `-e` causes the script to abort on the first command that returns a non-zero exit status. See [Advanced Bash Scripting Guide: Options](http://tldp.org/LDP/abs/html/options.html).

Since the `ping` command isn't executed, I guess `lxc exec pkg-builder-37 ip a add 10.214.101.2/24 dev eth0` is returning non-zero. On your `test.sh`, this is ignored and the script continues.

If you don't care if it returns non-zero, you can either remove the `-e` from the `bash` invocation, or change the line to something like `lxc exec pkg-builder-37 ip a add 10.214.101.2/24 dev eth0 || true`

By the way, if you don't need internal variables inside the heredoc, you might consider changing `"EOF"` to `EOF`. This would expand the variables before passing the script to the server and allow you to remove `env C_NAME=$C_NAME`

**Comment by palica** [comment]
So I changed the script now to:
```
#!/bin/bash

echo This script should start a container build a package and report back.

echo We are going to start container:
C_NAME=pkg-builder-$RUN
echo $C_NAME

echo Connecting to remote host and starting container

ssh root@10.214.101.1 /bin/bash -xe << EOF
        echo $C_NAME
        lxc launch -e -p prf-funtoo -p default fun-generic "$C_NAME"
        sleep 3
        lxc exec "$C_NAME" ip a add 10.214.101.2/24 dev eth0
        echo $?
        lxc exec "$C_NAME" -- ping -c3 10.214.101.1
        echo $?
        echo "Waiting 3 seconds"
        sleep 3
        lxc exec "$C_NAME" -- poweroff
EOF

```
Laminar:```

[laminar] Executing /var/lib/laminar/cfg/jobs/pkg-builder.run
This script should start a container build a package and report back.
We are going to start container:
pkg-builder-40
Connecting to remote host and starting container
pkg-builder-40
+ echo pkg-builder-40
+ lxc launch -e -p prf-funtoo -p default fun-generic pkg-builder-40
Creating pkg-builder-40


Starting pkg-builder-40
+ sleep 3
+ lxc exec pkg-builder-40 ip a add 10.214.101.2/24 dev eth0
```
Using remote script:
Job:
```
#!/bin/bash
echo Running on robor ...        
ssh root@10.214.101.1 /bin/bash -xe /root/test.sh
echo Done

```
remote script:```

#!/bin/bash   

        C_NAME=pkg-builder-1
        echo $C_NAME
        lxc launch -e -p prf-funtoo -p default fun-generic "$C_NAME"
        sleep 3
        lxc exec "$C_NAME" ip a add 10.214.101.2/24 dev eth0
        echo $?
        lxc exec "$C_NAME" -- ping -c3 10.214.101.1
        echo $?
        echo "Waiting 3 seconds"
        sleep 3
        lxc exec "$C_NAME" -- poweroff
```
output:
```
[laminar] Executing /var/lib/laminar/cfg/jobs/pkg-builder-remote.run
Running on robor ...
pkg-builder-1
+ C_NAME=pkg-builder-1
+ echo pkg-builder-1
+ lxc launch -e -p prf-funtoo -p default fun-generic pkg-builder-1
Creating pkg-builder-1


Starting pkg-builder-1
+ sleep 3
+ lxc exec pkg-builder-1 ip a add 10.214.101.2/24 dev eth0
0
+ echo 0
+ lxc exec pkg-builder-1 -- ping -c3 10.214.101.1
PING 10.214.101.1 (10.214.101.1) 56(84) bytes of data.
64 bytes from 10.214.101.1: icmp_seq=1 ttl=64 time=0.175 ms
64 bytes from 10.214.101.1: icmp_seq=2 ttl=64 time=0.067 ms
64 bytes from 10.214.101.1: icmp_seq=3 ttl=64 time=0.062 ms

--- 10.214.101.1 ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2077ms
rtt min/avg/max/mdev = 0.062/0.101/0.175/0.052 ms
0
Waiting 3 seconds
+ echo 0
+ echo 'Waiting 3 seconds'
+ sleep 3
+ lxc exec pkg-builder-1 -- poweroff
Done

```
Hm. the ip a add command returns 0 when running from remote script. I don't really understand. Thanks for the tips about bash -xe and EOF.

**Comment by ohwgiles** [comment]
Yeah that is weird. Can you try removing the `-e` from `ssh root@10.214.101.1 /bin/bash -xe` just to prove that this is the issue, and if so, the error code it returns might help diagnose the root cause

**Comment by ohwgiles** [comment]
But be careful, since you changed `"EOF"` to `EOF`, also the `$?` variables will be expanded before the script is passed to the server. You need to escape it like `\$?` or go back to `"EOF"`

**Comment by palica** [comment]
Same output, no error code.

**Comment by ohwgiles** [comment]
Hmm, I'm not sure how else to help. Did you try executing the laminar `.run` file directly yourself (not via laminar)? Or try the heredoc directly in a console?

**Comment by palica** [comment]
Direct run also doesn't work. Oh, well not too bad. I will workaround with the remote script that works well so far. Thank you for support.

**Comment by ohwgiles** [comment]
If you eventually figure this out I'd be interested in the solution. It's apparently not a laminar issue but since laminar encourages scripts as heredocs I can imagine this coming up again.

By the way, thanks very much for all your detailed issues, this is great QA and I think has really helped improve laminar.

**Comment by palica** [comment]
You are welcome, I didn't want to a be a big pain in the ...

ad heredoc: I will if I find a solution let you know. One thing that I also noticed eg. from your example on [Remote jobs](https://github.com/ohwgiles/laminar#remote-jobs) is that you have to use #!/bin/bash -e on your .run script or else the job will always succeed. So might want to put that somewhere in the docs, that the scripts have to provide a valid exit code when something goes wrong.

Thank you for you help and also for fixing and improving your very nice software.

**Comment by ohwgiles** [comment]
With 792c69a I added a note about `-e` under [Creating a job](https://github.com/ohwgiles/laminar#creating-a-job)
