### ISSUE TITLE
Environment file parsing issues

### ISSUE THREAD

**Issue by rerobins** [ohwgiles/laminar#120]
It would be nice to have the environment file be parsed by a shell in order to define the environment variables.  If not, then the documentation needs to be update so that users are not confused.  For example the following does not work as I had expected:

my_job.environment:
```
GOTIFY_TOKENS="token1"
```
This set the variable: `GOTIFY_TOKENS` to the string `"token1"` instead of stripping off the double quotes similar to what shell environments do.

**Comment by ohwgiles** [comment]
Having it parsed by a shell is not as simple as it sounds, and can open up several new cans of worms. I agree the documentation could be clearer about this though. PR welcome, otherwise I'll get to it in a month or two probably
