### ISSUE TITLE
How do I debug why my job never ends?

### ISSUE THREAD

**Issue by cweagans** [ohwgiles/laminar#122]
I have a job that runs once per week and pretty regularly just _will not end_. I had to `sudo kill -9 [pid]` to get it to stop, despite the job output having this:

```
==> Done
[laminar] sending SIGHUP to adopted child processes
[laminar] sending SIGKILL to process group 12068
```

The tail end of my script is like so:

```
format_text "heading" "Done"

# Trying this to make the job exit cleanly.
exit 0
```

(`format_text` is just a helper to add the `==>` in the output above). I've tried explicitly running `exit 0` to try to get the script to end, but it just won't.

I did this on my CI box:

```
root@ci:~# ps aux | grep laminar
[...]
root      5966  0.0  0.0   6144   820 pts/0    S+   21:21   0:00 grep laminar
laminar  12049  0.0  0.0  13176  3748 ?        S    Apr18   0:00 {laminar} my_job_name:9
[...]
```

This was the output _after_ laminar said it had sent SIGKILL to process group 12068. Once I ran `kill -9 12049`, the job ended and Laminar reported the job as aborted.

How do I go about debugging this further? I don't want to be manually killing processes on my CI box every week.

**Comment by ohwgiles** [comment]
This job leader feature is new in the latest release, so it might have some bugs still. First of all, let's see if there really is still a process hanging around that refuses to die. `ps -axf` is good for this because it clearly shows the parent relationships.

**Comment by cweagans** [comment]
Okay, I'll try that early next week if the job doesn't properly terminate and report back. Thanks!

**Comment by cweagans** [comment]
Aha! I found the culprit:

![image](https://user-images.githubusercontent.com/101590/80331494-6d687e00-8805-11ea-912d-3bd978542fbe.png)

Looks like some file encryption that i was doing was causing gpg-agent to start up and run in the background. I definitely understand why that would cause the job to not exit. Thanks for the pointer on `ps -axf` -- that really made it clear what was going on.
