### ISSUE TITLE
[A Solution] Docker container jobs not working...

### ISSUE THREAD

**Issue by stephengaito** [ohwgiles/laminar#125]
Hello, Many thanks for a very simple but *very very* useful tool.

I spent the day trying to get the `docker run` command to work inside a Laminar run script using your [existing documentation](https://laminar.ohwg.net/docs.html#Docker-container-jobs).

My problem was that the `docker run` would fail, turn into a 'defunct' 'zombie' process and the Laminar run script itself would fail to notice docker had exited.... forcing me to manually find the processes and kill them individually. Note that `laminar abort <jobName> <runNumber>` did not work.

After considerable googling, I finally tried wrapping the `docker run` command itself in a 'PID 1' process; to ensure all signals and, it turns out, stdin/stdout/stderr get passed between the Laminar run script and the `docker run` command.

Having done this, when `docker run` exits, the Laminar run script exits as well. Moreover, the `laminar abort` command also now works.

I am using [`dumb-init`](https://github.com/Yelp/dumb-init) as my 'PID 1' process wrapper. (I suspect you could use other 'PID 1' wrappers).

The minimal example that I finally found was:
```
#!/bin/bash -xe

# We start by creating the script used to control the docker image
#
cat <<DOCKER_SCRIPT > dockerScript
#!/bin/bash -xe

# This bash script is used *inside* a docker image to build pdf2htmlEX.

# We start by doing something simple
echo "Hello from test.run in Laminar!"

# Now try failing
#/bin/thisCommandShouldNotExist

DOCKER_SCRIPT

chmod a+x dockerScript

# Now run the docker image
#
dumb-init -v docker run --rm    \
  -v $PWD:/root                 \
  -v $WORKSPACE:/root/workspace \
  -v $ARCHIVE:/root/archive     \
  ubuntu:bionic                 \
  /root/dockerScript

echo "I am done!"
```
I found trying to pipe the DOCKER_SCRIPT directly into the `docker run` command, as suggested by your documentation, failed complaining of a lack of TTY (even when I used the `docker run -it` switch).

So instead I create the `dockerScript` bash script and then get `docker run` to run that. Among other things, this allows me to actually review the script that `docker run` was running.
 
Also notice that I have explicitly mounted the $WORKSPACE and $ARCHIVE in addition to the $PWD.

***Could you update your documentation?***

Many thanks for a great tool!

**Comment by stephengaito** [comment]
PS: I am using:
containerd 1.2.13
docker-ce/docker-ce-cli 19.03.11
on Ubuntu 19.10

**Comment by ohwgiles** [comment]
Hi, thanks for your detailed report and effort into finding a solution! Before updating the documentation, I'd like to understand the problem more deeply. I just tried the following `test.run`:

```
#!/bin/bash -ex
docker run --rm -i alpine <<EOS
foo
EOS
```

I get an immediately failing job with the expected console output

```
[laminar] Executing cfg/jobs/test.run
/bin/sh: foo: not found
```

Nothing gets stuck, there are no defunct processes, so I must be misunderstanding your problem or perhaps I have a different configuration. Can you help me reproduce your issue?

**Comment by stephengaito** [comment]
@ohwgiles, Many thanks for your minimal working example.

I have found from further use that the problem *is* 'PID-1' interaction (possibly between Laminar and Docker).  Wrapping all docker calls in a `dumb-init` 'PID-1' wrapper solves all problems in all modes (but might be overkill for some use cases).

SO, your specific use case (one way or another) pipes shell commands into the container's shell command. Used this way no 'PID-1' wrapper is needed.

However, if docker is used with a non-PID-1 aware process without being wrapped in dumb-init, when the docker command completes (either due to failure or success), the docker process becomes defunct and Laminar fails to notice that the over all job has finished.

One of the most important uses of docker used with a non-PID-1 aware process is where a non-PID-1 application has been wrapped up as a docker image (indeed this is scenario that I am ultimately using Laminar to build and test).

Here is a new minimally ***failing*** example:

```
#!/bin/bash -ex

cat  <<EOS > testScript
#!/bin/sh -xe

# This fails...
#foo

# This succeeds...
echo foo

EOS

chmod a+x testScript

# The following fails/succeeds AND
#    Laminar is able to see the job has finished
#
#cat testScript | docker run --rm -i --init -v $PWD:/root alpine

# The following fails/succeeds BUT
#    Laminar fails to see that the job is finished
#
docker run --rm -i --init -v $PWD:/root alpine /root/testScript
```
***Note*** that I have used docker's `--init` switch which is supposed to wrap the `/root/testScript` in a docker-internal PID-1 aware process.... but since this does not work... I suspect the real 'PID-1' problem is between Laminar and Docker, (rather than "inside" docker).

---

Again, many thanks for a lovely build/test tool. I have just looked at Circle-ci vs Travis (which my project already uses), but conclude that for the comprehensive building / testing / releasing I am after, Laminar is the way.

**Comment by ohwgiles** [comment]
The docker init problem discussed all over the internet is about correctly reaping all processes *within* the docker container. The problem you see is about the laminar run not properly reaping the `docker` process. Snipped output from `ps axf`:

```
S+     0:00  |  ./laminard -v
S      0:00  |   \_ {laminar} test:3
T      0:00  |       \_ /bin/bash /var/lib/laminar/cfg/jobs/test.run
Z      0:02  |           \_ [docker] <defunct>
```

This explains why adding `--init` to `docker` has no effect, because that affects only child processes of the container.

In this case, it is the responsibility of `bash` to reap `docker`. Alternatively, it could just exit, which would reparent `docker` to `{laminar}`, which would then reap it properly.

It looks like `bash` isn't reaping `docker` because it's waiting for data on `stdin`. I think you could argue that `bash` shouldn't do this, but most likely it has a good reason. The reason wrapping your call to `docker` in `dumb-init` "fixes" the issue is that it becomes the responsibility of `dumb-init` to reap `docker`, and it behaves differently from `bash`.

Anyway,  a better solution is just to drop the `-i` from `docker run`. You don't need it because you pass the script to be executed directly, whereas in my example it is needed so that docker passes the heredoc to the container bash. This makes your failing example work for me.

An even better solution would be to make this workaround unnecessary. After all, the problem isn't seen when running docker interactively from a terminal. It turns out that `stdin` is inherited all the way from `laminard`. Since it doesn't make sense for `laminard` to take `stdin`, it should provide `stdin` connected to `/dev/null` for its descendant processes. I'm surprised this wasn't done by your process manager, are you using `systemd` or something else? Anyway I'll push a fix to make sure this happens explicitly in laminar.

**Comment by stephengaito** [comment]
@ohwgiles 
>  I'm surprised this wasn't done by your process manager, are you using systemd or something else?

Alas, I am being a *very bad boy* and running `luminard` in "semi-continuous" mode in the foreground. I only need CI once in a long while (I have lots of other tasks which are not so heavily development focused). Running `laminard` in the foreground means that I can start it up when I need it, run some complex tasks, view the results, and then re-run the tasks (until they run correctly).

One feature, for me, of running `luminard` in the foreground is that I know where the results are, `/home/dev/luminar/tasks` and that if/when I want, I can completely clear out the luminar state (`rm -rf `) and start again with a completely clean setup.

> Anyway I'll push a fix to make sure this happens explicitly in laminar.

Unfortunately for me, your explicit mapping of `stdin` to `/dev/null` might preclude my use of 'Ctrl-C' on the command line to stop the foreground `luminard` process ;-(

However, I will no doubt find a work-around.

**Comment by ohwgiles** [comment]
> running luminard in "semi-continuous" mode in the foreground.

This explains why you see this issue. But it should be totally OK to run laminard like this, so it's still a valid bug.

> Unfortunately for me, your explicit mapping of stdin to /dev/null might preclude my use of 'Ctrl-C' on the command line to stop the foreground luminard process ;-(

No it won't. Ctrl-C causes bash to send SIGINT to the foreground process, it has nothing to do with stdin.

**Comment by stephengaito** [comment]
@ohwgiles, Many thanks for the fix.

I have now pulled your most recent github version (today) and compiled it, removed my "dumb-init" hack.... and all works beautifully.  I can even now "laminarc abort".
