### ISSUE TITLE
Currated collection of examples?

### ISSUE THREAD

**Issue by stephengaito** [ohwgiles/laminar#126]
Can your documentation, either directly, via your wiki, or via urls to other projects, provide a collection of example Laminar jobs....

This would be very helpful for new users, such as myself.

In case you are interested, (for good or for bad), I have decided to make my Laminar jobs public... 

See:
- https://github.com/stephengaito/laminar-scripts
- https://github.com/stephengaito/pdf2htmlex-laminar-scripts

Again, many thanks for such a simple but useful project.

**Comment by ohwgiles** [comment]
Thanks, I want to keep the documentation succinct and non-prescriptive, because everyone has very different ideas on how to write CI scripts and I don't want to favor any particular approach. Users will be able to find your examples by searching, thanks for sharing.
