### ISSUE TITLE
Broken output with laminarc show-jobs

### ISSUE THREAD

**Issue by transferkraM** [ohwgiles/laminar#127]
Hey guys,

I use docker based builds (`pkg/debian9-amd64.sh`) to package debs. Laminar is running on ext4 with relatime,data=ordered mount options.

Starting with 0.8 I've seen `laminarc show-jobs` to produce strange output, reproducable at the same job, e.g.

```
foo-bar
foo-foo
foo-fooa
�\���

bar-foo
bar-foobar
```

* **NOTE**: `foo-fooa` above should be `foo-foobar`.
* **NOTE**: There is a blank line after the "failed" job output

The issue persists up to current master (g6c61fb31).

Deleting the build files for the job in question provides the same result on the next job in alphabetic order. Looks like after reading some bytes something happens with some buffers.

**Comment by ohwgiles** [comment]
Thanks for spotting this. Should be fixed now.

**Comment by transferkraM** [comment]
Confirmed. Thank you!
