### ISSUE TITLE
[Workaround] Laminar not killing podman containers

### ISSUE THREAD

**Issue by stephengaito** [ohwgiles/laminar#129]
Hello (again),

For a large number of reasons, I have recently stopped using docker and am now using [podman](https://podman.io/) in rootless mode.

Unfortunately the changes you made to allow Laminar to kill docker containers.... is not quite enough to kill the podman variants.

Even worse when wrapped in a Podman (OCI) container, if my application's signal handler is invoked (and subsequently exits)  Laminar/Podman hangs waiting for something.... (The same Laminar jobs run with docker never hung)

The same conditions run with just Podman (and not inside Laminar) exits with the correct return code and does not hang... 

So there is an interaction between Laminar and Podman's signal handling which is going wrong ;-(

When, in my Laminar jobs, I (re)wrapped my calls to podman with [dumb-init](https://engineeringblog.yelp.com/2016/01/dumb-init-an-init-for-docker.html) everything works as expected... I can abort Laminar jobs, and failing applications (wrapped in Podman) exit as expected.

```
  dumb-init -v -- podman run <other arguments ....>
```

**SO... dumb-init is doing something that Laminar is not...**

Unfortunately, my setup is way too complex to build a minimal failing example... and I suspect podman's use is too small for you to worry about... so I will simply continue with my workaround.

Feel free to close this issue.... just note that something is not working in a minor case.

Again, many thanks for a wonderful tool!

Regards,
Stephen Gaito

(PS: I am using Laminar 0.9 recompiled yesterday from master).

**Comment by vvrein** [comment]
Hi!
Here just one more possible way to workaround things like these:
I'm using laminar to make backups on remote hosts.
On "shelter" host, laminar app as laminar user executes systemd-run ansible command as ansible user like this
`systemd-run --unit=backup_vr3.tort.icu --uid ansible --pty --wait --collect --service-type=exec --working-directory=/home/ansible/assets/ --setenv=ANSIBLE_FORCE_COLOR=true ansible -i hosts -u root 'servers[3]' -m shell -a /root/borg.sh`

So the main idea that we need something that starts, watch and handle all launched processes. And can kill all processes at once if needed.

**Comment by ohwgiles** [comment]
@stephengaito thanks for the report.

> Unfortunately, my setup is way too complex to build a minimal failing example... and I suspect podman's use is too small for you to worry about... so I will simply continue with my workaround.

podman is not such a niche program, and if it is affected, it is likely other programs are affected too. Laminar should reap child processes in the same way as dumb-init, so this is definitely a bug I would like to address.

@vvrein 

Using `systemd-run` breaks the process inheritance tree; you are actually using systemd as your supervisor rather than laminar. This could have some unexpected consequences like the failure of mutual exclusion mechanisms due to tasks running in the background and holding resources you expected to be freed.

> So the main idea that we need something that starts, watch and handle all launched processes. And can kill all processes at once if needed.

Laminar needs to be able to do this correctly. Any minimal failing examples would be appreciated.

**Comment by stephengaito** [comment]
@ohwgiles 

So *I think* the problem is in the rootless podman's interaction with the fuse-overlayfs (sub-system).

So to start with, my podman info is: [stephengaito-laminar-podman-info.txt](https://github.com/ohwgiles/laminar/files/4911073/stephengaito-laminar-podman-info.txt)

Things to note: I am running podman in rootless mode as the unprivileged user "laminar".

A "minimal" failing example seems to be:

```
#!/bin/bash

dumb-init -v -- podman run --rm -i \
  ubuntu:focal                  \
  /bin/bash  <<PODMAN_SCRIPT
#!/bin/bash

apt update

apt upgrade

apt -y install libreoffice-base-core

echo "All done!"

PODMAN_SCRIPT
```
The apt install of libreoffice is simply to get apt to install something complex. This forces podman to use the fuse-overlayfs.

I then attempt to use `laminarc abort` but this hangs.

IF I subsequently use `podman container list --all` to find the hanging container and then `podman stop `... 

The laminar job finally completes.

The other thing to note is that if I `laminarc abort` *before* apt starts the installation, `lamiarc abort` seems to work (with the help of dumb-init ... but not always without dumb-init).

However, *it seems* that, once fuse-overlayfs kicks in, not even dumb-init can kill the podman container....

I hope this helps!
