### ISSUE TITLE
Reverse Proxy: connection spinning

### ISSUE THREAD

**Issue by stephengaito** [ohwgiles/laminar#130]
Hello,

I am attempting to setup Lamnar (v0.9) as a reverse proxy behind an NGinx webserver (inside a rootless podman container -- all other NGinx based websites in this container are working correctly).

The external url is https based. The internal url is http.  (NGinx is providing the ssl setup).

When accessed completely locally (`http://10.0.0.1:8888`) everything works.

But when accessed via the NGinx frontend `https://laminar.perceptisys.co.uk` I get the main page "sketched" but then the "Connecting..." spinner just spins endlessly.

(Note laminar only runs when needed... so the `laminar.perceptisys.co.uk` site only works intermittently).

I am running `laminard` with the `-v` switch to get verbose output... and see only `laminard version 0.9 started`.

Any ideas on what I am doing wrong?

Regards,
Stephen Gaito

**Comment by vvrein** [comment]
Try set LAMINAR_BASE_URL to https://laminar.perceptisys.co.uk in laminar.conf.
Also, try turn on devtools in browser, switch to "network" tab, and reload laminar page. 
You would get something like this:
![image](https://user-images.githubusercontent.com/17022100/88266678-4290a780-ccd8-11ea-93f2-809837d10b91.png)
There you can see what requests gets failed.

**Comment by stephengaito** [comment]
The LAMINAR_BASE_URL is now https://laminar.perceptisys.co.uk and the result is the same:

[librarian-puma.stdout.log](https://github.com/ohwgiles/laminar/files/4965514/librarian-puma.stdout.log)

Any other ideas?

**Comment by vvrein** [comment]
Can you show your nginx config?

I was able to proxy laminar web interface with a such config:
```
server {
  listen 80;
  server_name laminar.shelter;
  location / {
        proxy_pass http://127.0.0.1:8080;
  }
}
```

https settings should not make any influence on webui, I think.
<details markdown='1'><summary>screenshots</summary>

![image](https://user-images.githubusercontent.com/17022100/88306856-ec415a00-cd13-11ea-8483-3b23bdd63ebe.png)
![image](https://user-images.githubusercontent.com/17022100/88306912-f95e4900-cd13-11ea-92cb-d71748fdec3c.png)

</details>

**Comment by ohwgiles** [comment]
You should not need to set `LAMINAR_BASE_URL` unless you are serving laminar from a subdirectory. See #80 for information about that.

The behaviour you see happens when the `text/event-stream` request isn't correctly passed through the reverse proxy. I think for nginx you may need to set

```
proxy_http_version 1.1;
proxy_set_header Connection "";
```

**Comment by ohwgiles** [comment]
@stephengaito did you solve this?

**Comment by stephengaito** [comment]
@ohwgiles sorry for the delay... I was on a walking holiday...

I have just now added your suggestion and unfortunately I still get the same response.

My nginx configuration file is:

```
server {
  listen 443 ssl;
  server_name laminar.perceptisys.co.uk;

  access_log /var/log/nginx/laminar.access.log;
  error_log  /var/log/nginx/laminar.error_log  debug;

  location / {
    proxy_http_version 1.1;
    proxy_set_header Connection "";
    proxy_pass http://w.x.y.z:8888/;
  }
}
```
With "w.x.y.z" replaced with the real (local) ip address

**Comment by vvrein** [comment]
@ohwgiles 
I've tried to proxy laminar with nginx & ssl and got the same result.
Found this in laminar's journal.
```
Aug 10 13:51:39 shelter laminard[362]: stack: b6d0fbc8 b6d0fbdc
Aug 10 13:51:39 shelter laminard[362]: kj/compat/http.c++:5079: error: unhandled exception in HTTP server; exception = kj/compat/http.c++:1852: failed: previous HTTP message body incomplete; can't write more messages
```

**Comment by vvrein** [comment]
I think I got it solved
When I tried same config with ssl, I got same result - spinning wheel.

**Comment by ohwgiles** [comment]
Aha! Thanks @vvrein for your assistance, this looks just like #88. If this is the case, adding `proxy_buffering off` could be avoided by setting `X-Accel-Buffering: no` in laminar's http response headers.

**Comment by ohwgiles** [comment]
@stephengaito could you please try with the latest master, with your original unchanged nginx config?

**Comment by stephengaito** [comment]
@vvrein many thanks for identifying the root problem

@ohwgiles (as always) many many thanks for a swift fix!

My installation now works perfectly with my original nginx configuration.

(And the new UI looks great!)

**Comment by TafkaMax** [comment]
I can't get laminarc to work with reverse-proxy.

![image](https://user-images.githubusercontent.com/46354923/126168170-7256277b-93c1-431b-b6d0-fd8cd6a0da7f.png)

![image](https://user-images.githubusercontent.com/46354923/126168269-3ed44a4a-cca8-4898-b4be-211ee1933062.png)

![image](https://user-images.githubusercontent.com/46354923/126168337-0317aa56-fbe8-45b2-ba95-4830ecd717e6.png

![image](https://user-images.githubusercontent.com/46354923/126168448-7ecc41ec-0b2f-4174-9e5a-eedafc906582.png)

I feel I've done everything correctly.

**Comment by ohwgiles** [comment]
@TafkaMax Try setting `LAMINAR_BASE_URL=/laminar/` (note the trailing slash). See https://stackoverflow.com/a/26043021

**Comment by TafkaMax** [comment]
> @TafkaMax Try setting `LAMINAR_BASE_URL=/laminar/` (note the trailing slash). See https://stackoverflow.com/a/26043021

Thanks for the response! I already went the route with a subdomain rather than subdirectory, but I will try this with my next instance of laminar I will be setting up soon.
