### ISSUE TITLE
'LAST_RESULT' is always 'unknown'

### ISSUE THREAD

**Issue by BrightSeraph** [ohwgiles/laminar#131]
Thank you for this sleek ci system which I use on a daily basis.

I am a gentoo novice (I use it, but I am currently not yet enough to write my own ebuilds) - so I currently build laminar by myself.
Within my system there are following dependencies installed:
- capnproto v0.7.0
- rapidjson v1.1.0

As a test i have a script that build laminar itself within 3 steps:
- .before clones the repository from GitHub
- .run builds with tests and executes them
- .after just echoes JOB RUN RESULT and LAST_RESULT

 LAST_RESULT is always 'unknown' (independently of the last run - may it be successful or failed)

Steps to reproduce:
- build & install (git head) laminar
- write a job with before- (not sure wether this is necessary), run- and after-script
- check LAST_RESULT within after-script

Expected behavior:
LAST_RESULT contains the string 'failed', 'successful' or 'aborted' depending on the result of the last run

Observed behavior:
LAST_RESULT always contains 'unkonwn'

laminar.before
```bash
git clone https://github.com/ohwgiles/laminar src
```

laminar.run
```bash
#!/bin/bash -xe

cmake \
   -G Ninja \
   -DCMAKE_BUILD_TYPE=Release \
   -DCMAKE_INSTALL_PREFIX=/usr \
   -DBUILD_TESTS=TRUE \
   src

cmake --build .

./laminar-tests
```

laminar.after
```bash
#!/bin/bash -xe

echo "$JOB $RUN: $RESULT ($LAST_RESULT)"
```

//EDIT:
laminar version: 
0.9-7-gdc3e41fb

**Comment by ohwgiles** [comment]
Thanks for the detailed report. Fixed now. Be aware that `LAST_RESULT` is set at the time the job starts to the result of the last completed build *at that moment*, so if you have multiple runs of the same job overlapping in time, its value might not be what you expect.

**Comment by BrightSeraph** [comment]
Thanks for the quick fix, I can confirm it works (for me) ;)
I almost always run builds sequentially (without overlapping job queuing) and want to be able to reschedule a failed job if it failed for the first time (since on my other project there are some flapping jobs).
Also I want to be able to implement the notification stuff you mentioned within your documentation (when the status of a job changed)
Thanks for the hint with overlapping jobs - I will keep it in mind.

Just by the way - clang refuses to compile (if that is something you are interested in - I will submit another bug for that)

**Comment by ohwgiles** [comment]
> I am a gentoo novice (I use it, but I am currently not yet enough to write my own ebuilds) - so I currently build laminar by myself.

You may be interested in [these](https://github.com/ohwgiles/laminar/issues/7#issuecomment-338924063); although they might need to be updated.

> clang refuses to compile (if that is something you are interested in - I will submit another bug for that)

Please do.
