### ISSUE TITLE
[Bug] In job history bars are reversed relating to numbers

### ISSUE THREAD

**Issue by vvrein** [ohwgiles/laminar#132]
![image](https://user-images.githubusercontent.com/17022100/93853839-454e4f80-fcbd-11ea-99da-888e57c8ead7.png)
The last failed job is `#122`, but on bars it marked as `#107`
Second last is `#117`, but marked as `#112`

In a nutshell:
Bars is going right to left
Nums is going left to right

Laminar: latest from master

Could https://github.com/ohwgiles/laminar/commit/4b62e6dbf332b6b852973fae08b73751a23578af be the root of the problem?

**Comment by ohwgiles** [comment]
I'm pretty sure `.reverse()` is correct here, and it works for me. Can you check the actual javascript you receive in the browser dev tools to see whether `.reverse()` is present on that line? Perhaps an old version of the javascript is cached by your browser or reverse proxy?

**Comment by vvrein** [comment]
Yup, you are right! My browser cached the js code.
Thanks!
