### ISSUE TITLE
running jobs on Windows 

### ISSUE THREAD

**Issue by simevo** [ohwgiles/laminar#133]
is there any previous art / best practice for running remote jobs on Windows ?

**Comment by stevenkl** [comment]
You could setup a ssh-server on your windows machine and use it the same way you would use a remote linux machine, the only difference to keep in mind is the windows shell (cmd/powershell).

Greetings.

**Comment by ohwgiles** [comment]
You might try winexe

**Comment by simevo** [comment]
ssh is now "supported" by Microsoft so I think it's the path to follow.

I [RTFM](https://docs.microsoft.com/it-it/windows-server/administration/openssh/openssh_server_configuration) although ATM that's in part obsolete ([PR](https://github.com/MicrosoftDocs/windowsserverdocs/pull/4788) is pending).

In a nutshell, type this in a privileged powershell prompt:

    Add-WindowsCapability -Online -Name OpenSSH.Client~~~~0.0.1.0
    Add-WindowsCapability -Online -Name OpenSSH.Server~~~~0.0.1.0
    Set-Service -Name sshd -StartupType 'Automatic'
    Start-Service sshd

Then as usual copy the remote public keys in `.ssh\authorized_keys` in the the user's profile folder.

Except that if the user you are ssh-ing to is a local administrator of Windows, you should copy them to `C:\ProgramData\ssh\administrators_authorized_keys` instead, and fix the ACL for this file (RMB click, Properties, "Security" tab, click "Advanced", click "Change permissions", disable inheritance "converting inherited permissions into explicit permissions on this object", remove any access rights for "Authenticated Users", then Apply and OK twice).

After this, I can ssh into the windows machine, get `cmd.exe` as default shell and happily launch BATch files like it's 1992:

    scp test.bat simevo@W10-64-VS2019:.
    ssh simevo@W10-64-VS2019 test.bat x64 release

This fits well with the way laminar handles [Remote jobs](https://laminar.ohwg.net/docs.html#Remote-jobs).
