### ISSUE TITLE
Failing to run the "Defining a job" example

### ISSUE THREAD

**Issue by tcassaert** [ohwgiles/laminar#135]
I came across this very cool project and wanted to try it out for in my homelab. 

I created a docker image to run the laminard service:
```
docker build -t laminar:latest -f docker/Dockerfile
```
then I ran the image with:
```
docker run -it -p 8080:8080 laminar:latest
```
I can access the web UI, so that seems to work fine.

Then I added following script:
```
#!/bin/bash -ex
wget ftp://ftp.gnu.org/gnu/hello/hello-2.10.tar.gz
tar xzf hello-2.10.tar.gz
cd hello-2.10
./configure
make
```
to `/var/lib/laminar/cfg/jobs/hello.run` and made it executable.

With `laminarc run hello` I tried to start the build, but it fails instantly with:
```
[laminar] Executing cfg/jobs/hello.run
[laminar] Failed to execute cfg/jobs/hello.run
```
Running the server with `-v` for more output shows this in the logs:
```
rpc.cpp:85: info: RPC run; jobName = hello
laminar.cpp:672: info: Started job; run->name = hello; run->build = 1; ctx->name = default
laminar.cpp:713: info: Run completed; r->name = hello; to_string(r->result) = failed
run.cpp:77: info: Run destroyed
```

**Comment by ohwgiles** [comment]
Please carefully read the [relevant section of the manual](https://laminar.ohwg.net/docs.html#Building-for-Docker).

Docker provides filesystem isolation, meaning `/var/lib/laminar` as seen by `laminard` is not the same as your host `/var/lib/laminar`. To allow the container access to your host `/var/lib/laminar`, add `-v /var/lib/laminar:/var/lib/laminar` to your `docker` invocation. Be aware that you will also need to grant more liberal permissions to the host's `/var/lib/laminar` to allow the containerized laminar to write there.

**Comment by tcassaert** [comment]
I'm aware that I can't access host directories in a container without mounting them... But this is without a mount. I created the files in the container where the laminard server is running, so it should be able to access them. They are also created with the `laminar:users` ownership.

If I would try to run something without it being present in the correct dirs, I would get:

```
laminarc run test
Failed to start job 'test'
```
But in my case, it does find it, tries to start it, but fails immediately with:
```
[laminar] Executing cfg/jobs/hello.run
[laminar] Failed to execute cfg/jobs/hello.run
```
presented in the UI.

**Comment by ohwgiles** [comment]
Ah ok, apologies, from your description it seemed like you made them outside.

My next guess would be that your shebang is `#!/bin/bash` and the alpine container only has ash or something?

**Comment by tcassaert** [comment]
Ok, that's a stupid mistake from my end... It's indeed just the `#!/bin/bash` that could not be found. 

Thanks for pointing that out!
