### ISSUE TITLE
Docker build is not reading /etc/laminar.conf

### ISSUE THREAD

**Issue by marcopullo** [ohwgiles/laminar#136]
For some reason the current `docker/Dockerfile` is causing `laminard` to not read any configuration from `/etc/laminar.conf` (tried on `head` and `0.90`).

Repro steps:
```
git clone https://github.com/ohwgiles/laminar.git
docker build -t laminar:latest -f docker/Dockerfile .
# put any modifications into `laminar.conf`, e.g. `LAMINAR_TITLE=testing` or `LAMINAR_KEEP_RUNDIRS=10`
docker run -d --name laminar_server -p 8080:8080 -v $(pwd)/laminar.conf:/etc/laminar.conf laminar:latest
# go in and note Laminar website title does not change to `test`, nor are any run files kept after runs are completed
```

Glancing at the code base there's nothing obvious unless the conf file is broken. Even without mounting `laminar.conf` as volume and just entering the container and changing `/etc/laminar.conf` directly and restarting `laminard` does not get it to read the `laminar.conf` settings.

In the meantime, a workaround is to just pass in the conf file as an environment file via docker itself. e.g.
```
docker run -d --name laminar_server -p 8080:8080 --env-file laminar.conf laminar:latest
```

But it would be better if it read the `/etc/laminar.conf` as expected.

PS. loving the simplicity ethos of Laminar! Nice work!

**Comment by ohwgiles** [comment]
Yeah, actually `laminard` does not read `laminar.conf` at all, it expects all the variables there to be passed in by systemd or other init system, see [the unit file](https://github.com/ohwgiles/laminar/blob/master/etc/laminar.service.in#L7).

I think your workaround is a good solution, and the documentation should just be updated to mention this. Sound ok?

**Comment by marcopullo** [comment]
Ah, so laminar was even more minimal than I knew :)

Yup, documentation update sounds good.
