### ISSUE TITLE
CentOS 7 build for Release 1.0

### ISSUE THREAD

**Issue by frankfil** [ohwgiles/laminar#142]
There is no CentOS 7 RPM for the 1.0 release at https://github.com/ohwgiles/laminar/releases/tag/1.0

Is there no build for CentOS 7 or did it just go missing?

**Comment by ohwgiles** [comment]
I didn't bother with it at first because I figured most had moved to CentOS 8 by now, but since the whole CentOS Stream thing I guess there will be lots of CentOS 7 holdouts. Package built and uploaded.

**Comment by frankfil** [comment]
Thank you.

We were actually days away from installing our first CentOS 8 VMs when the CentOS Stream announcement was made so as you guessed we're sticking with 7 for a bit longer as we reevaluate our options.
