### ISSUE TITLE
Maybe list artifacts recursively?

### ISSUE THREAD

**Issue by jbglaw** [ohwgiles/laminar#149]
Hi!

Building binutils/gcc/..., I usually encounter `*.log` files (from `configure`) and `*.sum` files (test results from `dejagnu`). These are from within different directories. I found it convenient to just `find . -type f -name '*.log' -exec cp --parents {} "${ARCHIVE}"` (same for `*.sum`), so they, despite having basically all the same name, show up in different directories (resembling the original source / build tree.)

Right now, `laminard` will only list files directly within the job's archive directory, ignoring subdirectories. Maybe a patch (see attached) for recursing into the artifacts dir would be acceptable?

Thanks,
  Jan-Benedict
[laminar-recursive-artifacts.txt](https://github.com/ohwgiles/laminar/files/6095987/laminar-recursive-artifacts.txt)

**Comment by ohwgiles** [comment]
Looks fine to me. Please open a PR, or alternatively send a patch with a full git header so your authorship is recorded.

**Comment by jbglaw** [comment]
Pull request sent. Changed it a little to default-initialize the subdir to ".", so there's no need to change the callers.

**Comment by ohwgiles** [comment]
Resolved in #150
