### ISSUE TITLE
Following log output

### ISSUE THREAD

**Issue by jbglaw** [ohwgiles/laminar#151]
Hi!

It seems you cannot follow log output for many concurrent jobs in multiple browser tabs right now, because log output is streamed (chunked transfer) through a persistent connection. As today's browsers limit the number of connections to a target (usually to a very low number), you cannot easily follow many (parallel) builds.

So while doing a chunked transfer is quite neat (no need for re-establishing the connection every other second to poll for updates), it quite limits the number of logs you can watch.

I'd like to discuss/propose another (alternative) way to get the (new) parts of a build log by polling. While less efficient, it'd scale to quite many more logs.

**Comment by ohwgiles** [comment]
The chunked transfer is also great for watching logs with curl, which obviously doesn't have the multiple connection issue.

You probably want to run laminar behind a reverse proxy anyway; maybe it can be responsible for providing HTTP/2 (assuming that these limits go away there) and can then be configured to open more HTTP/1.1 connections to `laminard`

**Comment by jbglaw** [comment]
On a quick try, I failed to get the path component fixed properly for a configuration behind a Nginx proxy (using the Debian package), I'll probably give it a longer try these days. My issue her was that the page itself loaded properly and found all referenced intividual files, but I couldn't get anything other than the initial overview page to work properly. If the browser manages to squeeze all requests into one HTTP/2 connection, that might actually work. (At least as long as the Nginx proxy doesn't limit connections to the laminard though.)

**Comment by ohwgiles** [comment]
Maybe [this comment](https://github.com/ohwgiles/laminar/issues/115#issuecomment-595738559) would be helpful.

Laminar could definitely use some documentation on how to configure a reverse proxy...

**Comment by jbglaw** [comment]
> The chunked transfer is also great for watching logs with curl, which obviously doesn't have the multiple connection issue.

I tried, but failed here. How do I invoke curl correctly to follow a log?

**Comment by ohwgiles** [comment]
Just `curl $LAMINAR_HTTP/log/$JOB/$RUN`. Log output should be delivered to your console as it is produced, as long as your reverse proxy doesn't interfere.

**Comment by ohwgiles** [comment]
Is this issue still relevant?

**Comment by jbglaw** [comment]
Good question... I haven't yet really pushed towards running behind a proxy, which (with h/2) could probably fix the connection limit a browser will impose.

As a side note though, I've seen several times that just `curl`ing (as above) for a run's output not always works as expected. Quite often, I just got that was already there, but it didn't follow. Haven't debugged this any further. Though these build logs are quite large, they typically end up somewhere between 100 and 200 MB.

**Comment by jbglaw** [comment]
I gave this a try. From a view at a curl strace, in the working case, the initial large chunk is transferred and finished with `\r\n`, leading curl to expect the next chunk.

In a non-working case, curl's `recvfrom` fetching the last part of the initial chunk _also_ contains the next chunk, which is announced as size 0 (and finished within this `recvfrom` with another `\r\n`.) My guess is that this happens when the job produces further log output while the initial chunk is being sent.

**Comment by ohwgiles** [comment]
Does your build contain commit b16991b17ae24265b73cca134088804bc66b6919? I cannot reproduce this nor can I see how that could happen from the code.

After a request for a log endpoint, the existing log is *copied* at [http.cpp:226](https://github.com/ohwgiles/laminar/blob/b16991b17ae24265b73cca134088804bc66b6919/src/http.cpp#L226), then the requester is added to a list of watchers immediately at [http.cpp:233](https://github.com/ohwgiles/laminar/blob/b16991b17ae24265b73cca134088804bc66b6919/src/http.cpp#L233) without returning to the event loop.

On the receive side, when output is read from the child process, the new chunk is added to the total buffer at [laminar.cpp:663](https://github.com/ohwgiles/laminar/blob/b16991b17ae24265b73cca134088804bc66b6919/src/laminar.cpp#L663), and again, without entering the event loop, a *copy* of the chunk is sent out to subscribed watchers at [laminar.cpp:664](https://github.com/ohwgiles/laminar/blob/b16991b17ae24265b73cca134088804bc66b6919/src/laminar.cpp#L664).

This is a pretty serious sounding issue, so I would like to have it understood.

**Comment by jbglaw** [comment]
It does! That's an improtant patch in my setup, it's crashy without that patch. What I'm *running* right now it the Debian "unstable" source (https://salsa.debian.org/meskio-guest/laminar.git) plus three patches:

1. The "allow subdirs in artifacts" patch (already upstream);
2. the above mentioned fix (upstream; without it, laminard crashes too often; and
3. then "make taskFailed non-fatal" patch (upstream as well.)

The Debian package is IMHO based on b755a2ef. Later on (up to HEAD), there seems to be no additional patch of relevance. Also, (almost?) all further patches are also as a patchqueue series in the Debian package, so there should be no real diff remaining. At least not wrt. the backend AFAICT. The most interesting probably is the vast amount of jobs defined (nearly 1000), mostly running eight in parallel, and they really produce output.

I've been running two instances (IPv{4,6} toolchain.lug-owl.de:8080 and IPv6-only toolchain2.lug-owl.de), the former crashed (needs restart), the other is accessible (with IPv6.) It's located in my basement. Calling curl (through Wifi and GigE) (ie. `curl --silent http://toolchain2.lug-owl.de:8080/log/netbsd-evbsh3-sh3eb/4`, the download and dumping-to-xterm takes some 5 sec, resulting in 65 MB output (run "just" started, so it's not too much.)  I can observe the behavior basically every time (right now.) If I `kill -STOP` some part of the build stuff of this build and run `curl --silent...`, it'll dump all the former log and sit there. `kill -CONT` will start output on the curl side.

**Comment by jbglaw** [comment]
Version 1.2 sneaked into Debian unstable, that seems to work quite well. So I'm to close this issue. Thanks a lot!
