### ISSUE TITLE
laminarc: Option to un-queue a queued job

### ISSUE THREAD

**Issue by jbglaw** [ohwgiles/laminar#155]
Hi!

This is quite on the wishlist-side of life: Sometimes it'd be quite handy to have a chance to remove a queued job. What's your option about this?

> root@toolchaintest-host:~# laminarc show-jobs |wc -l
> 869
> root@toolchaintest-host:~# laminarc show-queued|wc -l
> 227

Quite often, I'd like to re-schedule, but that won't work right now. On the current hardware, these jobs may each run in the hours, so waiting for a full cycle is a daunting task. Though due the crashes (or port-8080-unavailability after exception) I can redo the schedule quite often.

Thanks, Jan-Benedict

**Comment by ohwgiles** [comment]
`laminarc abort` works on queued jobs since 06a5f3d8ef3e0b799a. Am I missing something?

**Comment by jbglaw** [comment]
Seems so! This wasn't at all obvious to me, because `laminarc show-queued` only names the job names, but not their run numbers. But `laminarc abort` requires these, so it's kind of hard to do something like

> laminarc show-queued | grep '^binutils' | while IFS=: read JOB NUM trash; do
> laminarc abort "${JOB}" "${NUM}"
> done

...and the web FE also doesn't show job numbers. So the only way is tracking them? Or pulling them from the database?

**Comment by ohwgiles** [comment]
Assigning numbers to queued jobs is a relatively new change in laminar, I think the fact that `laminarc show-queued` does not show their numbers is an oversight and should be fixed.

I am not sure if showing them all on the web frontend is a good idea (at least not on the main page). It could take up a lot of valuable vertical space. Open to suggestions of how to do this effectively.

**Comment by jbglaw** [comment]
In the web frontend, why not just display them right the same way as with finished or running jobs? I don't see how that'll claim additional vertical space: As finished, running and queued jobs are listed, it seems it's all one-liners. And their (horizonthal) with is, if at all, dominated by finished/running jobs as their job name is already extended by `#nnn`, so there's no additional space taken (that's not already claimed.)

**Comment by ohwgiles** [comment]
Ah, you are right, I was remembering the job-specific page which collapses multiple queued jobs as "#n jobs queued".

Happy to accept a PR that fixes this, would have to be in at least these places:
- the main page
- the job-specific page
- the output of `laminarc show-queued`

Otherwise I will get to it someday...
