### ISSUE TITLE
Unable to run two instances on the same machine

### ISSUE THREAD

**Issue by thomas-mc-work** [ohwgiles/laminar#157]
When I start a second instance with a separate configuration (and of course a different port) I always receive this error:

    fatal: ::bind(sockfd, &addr.generic, addrlen): Address already in use; toString() = unix-abstract:laminar

The two instances are running within their specific users. So there can be no environment blending issues.

This only happens when another instance is running. Starting them separately is working fine.

**Comment by ohwgiles** [comment]
Laminar listens on two transports; one for HTTP requests to the web UI (controlled with `LAMINAR_BIND_HTTP`) and one to receive commands from `laminarc` (controlled with `LAMINAR_BIND_RPC`). It looks like both laminar instances are trying to use the same bind address for the latter.

[Here](https://laminar.ohwg.net/docs.html#Reference) is the relevant reference from the docs.

**Comment by thomas-mc-work** [comment]
Wonderful, thank you for that very quick reply!
