### ISSUE TITLE
Change permissions for LAMINAR_BIND_HTTP socket file

### ISSUE THREAD

**Issue by dancojocaru2000** [ohwgiles/laminar#160]
Hello. It would be very useful if in the laminar configuration there would be an option to choose the mask for the socket file.

At the moment, the mask seems to be 755, which is pretty useless since that means only `laminar` the user can send data through it. This, for example, prevents Nginx from using it.

**Comment by ohwgiles** [comment]
Agreed. Actually I'm struggling to think of any reason not to just hard-code it to `660`. In any case, the unix socket creation mechanism is provided by capnproto, which also does not supply an API to change the permission mask, so I'm checking whether it's appropriate to address that there. If not, I will work around that in laminar.

In the meantime, two workarounds you could consider are either changing `umask` (with [this directive](https://www.freedesktop.org/software/systemd/man/systemd.exec.html#UMask=) if you use systemd) to `002`, or just calling `chmod` after starting laminar (perhaps using [`ExecStartPost`](https://www.freedesktop.org/software/systemd/man/systemd.service.html#ExecStartPre=) if using systemd)
