### ISSUE TITLE
Link to queued jobs is double escaped

### ISSUE THREAD

**Issue by sbrl** [ohwgiles/laminar#161]
When queueing a subjob from a main job, the text in the log that links to the sub-job is double escaped.

Example image:
![image](https://user-images.githubusercontent.com/9929737/133948146-1288a347-1624-457c-89b8-9db74db40e15.png)

I can confirm this is an issue in the 1.1 release and was not an issue in the release prior to that.

**Comment by ohwgiles** [comment]
Confirmed, should be a simple fix...
