### ISSUE TITLE
Changing queue order

### ISSUE THREAD

**Issue by jbglaw** [ohwgiles/laminar#162]
Hi!

My toolchain testing stuff is, by now, quite well-working. It has a good number of jobs:
```
root@wolf:/var/lib/laminar/cfg [master] # laminarc show-jobs |wc -l
1549
```

Usually, I just queue them all at once, in a somewhat meaningful order:
```
root@wolf:/var/lib/laminar/cfg [master] # laminarc show-jobs |cut -f 1 -d - |sort|uniq -c
      5 admin
    211 binutils
      7 dockerbuildimage
    212 gas
    217 gcc
    205 gdb
    428 linux
     93 netbsd
     93 nnetbsd
     78 simh
```
That is, I schedule all `dockerbuildimage`s first and wait for completion. Then, I let the `admin` jobs run (which symlink all other jobs in place). Finally, the Binutils-related jobs are started (`binutils`, `gas`, `gdb`), once finished `gcc`, and once that's fnished, I queue in all the others (`linux`, `netbsd`, `nnetbsd` (building the NetBSD distro within a NetBSD KVM) and the `simh` builds.

With that many targets, I quite often encounter new build issues (after all, that's what it's all about!). Most of these are small issues that could easily be solved. All jobs have the ability to pull in patches (named after the `$JOB` name), which I'd like to verify quickly to publish them on the relevant mailing lists.

However, with all the jobs queued, it takes several days to work down the queue, so I usually have to wait a few days to be able to test my stuff. I can, theoretically, invoke the job's scripts manually, but that way there's no documentation about this run.

It would be great to extend `laminarc` to re-schedule a specific queued job to the top of the list, so that it's build right away once a slot gets available. It's a simple patch I think (I've done a bit of it), but I fail to change the queue. For the time being, I've settled to use `ts` (possibly called `tsp`, located in the `task-scheduler` package) where I've created a queue with as many slots as I have available for Laminar, and instead of `laminarc queue .....`, I enqueue the jobs to `tsp` using `tsp laminarc run ...`. That way, I can, later on (for tesing paches) enqueue the job again and mark it as urgent (`tsp -u ...`), which has the effect of pushing that job to the top of `tsp`s queue.

While that workaround works for sure, there's no longer any indication (web frontend) about the remaining queue of jobs for this whole 1500 runs queue, just because the jobs aren't queued any longer in advance.

**Comment by ohwgiles** [comment]
This seems reasonable. Something like `laminarc queue --first` or `laminarc queue --next` maybe.

I thought about whether there is a more generic problem that can be solved here. Maybe instead you could create a context for these cases, and laminarc could grow an option to assign a job to a context that it wouldn't normally. The downside for your use case would be potential oversubscription. I'm also not convinced that this idea would open up other valid use cases or just make it easier to make a mess.

Which is to say, so far I prefer the simpler queue-to-front idea...

**Comment by ohwgiles** [comment]
@jbglaw would appreciate your feedback on the implemented feature
