### ISSUE TITLE
fatal: ::read(fd, buffer, maxBytes): Connection reset by peer

### ISSUE THREAD

**Issue by ohwgiles** [ohwgiles/laminar#164]
Beginning a new issue for the problem reported by @jbglaw and discussed at #146 after the issue was initially closed.

Under some circumstances, Laminar may catch a fatal exception and exit with this output: `fatal: ::read(fd, buffer, maxBytes): Connection reset by peer`.

The original error causing the exception comes from [here](https://github.com/capnproto/capnproto/blob/v0.7.0/c%2B%2B/src/kj/async-io-unix.c%2B%2B#L301), when `read` returns `-1` with `errno == ECONNRESET`.

In 02810309fcfe09f1b4eb283625d656260d0690ef I made the error non-fatal, but then the http server stops accepting new connections.

**Comment by ohwgiles** [comment]
The underlying behavior of the `kj` library is being investigated [here](https://github.com/capnproto/capnproto/issues/1219).

In the meantime, this issue can be addressed in laminar by catching this exception and restarting the http server.

**Comment by maralorn** [comment]
Hey @ohwgiles, thank you for this fix! I have continuous problems with this issue for quite a while.

Do you maybe plan to do a bug fix release soon? That would be awesome!

I maintain laminar in nixos and observe about on laminar crash per day on my personal server. So I would prefer to not expose our users to this problem for much longer. If you tell me that it will be a while until the next release, I will consider applying some patches downstream.

**Comment by ohwgiles** [comment]
Thanks for maintaining the nixos package! I intend to have a release out within a week or so.
