### ISSUE TITLE
Reload config file, not restart on SIGHUP

### ISSUE THREAD

**Issue by KAction** [ohwgiles/laminar#166]
Conventionally, unix daemons reload their config files on sighup. Laminar does otherwise -- it terminates.
Any change to get it to follow the convention?

I just stumbled upon it when I got job that refreshes SSL certificates and sighup all daemons on multiple systems. One of them was the system that was running laminar itself. I worked around by excluding Laminar, but having all daemons behave same way would be awesome.

Thank you again for your work!

**Comment by ohwgiles** [comment]
> Conventionally, unix daemons reload their config files on sighup.

While common, this is definitely not universal. Apache, for instance, uses `SIGUSR1` to reload config.

> Laminar does otherwise -- it terminates.

Of course, this is the default action for `SIGHUP`.

> sighup all daemons

Out of interest, how do you implement this? How do you know which processes are "daemons", and avoid e.g. sending `HUP` to a currently running job (child process) of `laminard`? Seems a safer option would be to explicitly list the processes which need to be reloaded when certs are updated....

All that being said, ignoring `SIGHUP` is a reasonable thing for a daemon process to do, so `laminard` could do that. It does not need a "reload config" action.

**Comment by KAction** [comment]
> > sighup all daemons
> 
> Out of interest, how do you implement this? How do you know which processes are "daemons", and avoid e.g. sending `HUP` to a currently running job (child process) of `laminard`? Seems a safer option would be to explicitly list the processes which need to be reloaded when certs are updated....

I use runit(8) supervision suite. Every daemon managed by runsvdir(8) has directory in /service, so you can do mass operations with "sv hup /service/*". Or "sv hup /service/nginx-*"
=> http://smarden.org/runit/sv.8.html

> All that being said, ignoring `SIGHUP` is a reasonable thing for a daemon process to do, so `laminard` could do that. It does not need a "reload config" action.

Fair enough, although I would write 'Laminar don't have config to reload, SIGHUP is ignored' on stderr on sighup. That would have saved me from half-an-hour to hour of debugging today.

**Comment by KAction** [comment]
https://github.com/ohwgiles/laminar/pull/167
