### ISSUE TITLE
Laminar Runs on FreeBSD (with Caveats)

### ISSUE THREAD

**Issue by bedwardly-down** [ohwgiles/laminar#169]
Hey there. I’ve been experimenting with getting Laminar running on my FreeBSD server inside of jails and made some headway with it using both the builtin [Linux compatibility layer](https://wiki.freebsd.org/Linuxulator) and the debootstrap pkg to get a mostly functional [Ubuntu Focal instance](https://www.micski.dk/2021/12/21/install-ubuntu-base-system-into-freebsds-linux-binary-compatibility/) running. The binaries run directly in FreeBSD when called from the system but seem to ignore all environment variables and config files so far. The compatibility layer must be set and installed in the host directly but mounting the /compat/ubuntu folder in rw mode for the jail seems to be all that’s required to get it working on that front.

Any tips or questions are welcomed. I’d love to get it fully functional on FreeBSD but would have no clue how to port it over directly; this is the next best thing, impo.

**Comment by ohwgiles** [comment]
I haven't used FreeBSD so can't help much sorry. Laminar does use a few features that I believe are Linux-specific, such as [this](https://github.com/ohwgiles/laminar/blob/99e2e629063a10059ee33ed3d68fcdde61dab12e/src/leader.cpp#L320), but I think they should be able to be stubbed out on BSD without losing critical functionality.

I would suggest starting with a build from source and seeing where the build failures are.

**Comment by bedwardly-down** [comment]
Possibly solved with my current PR https://github.com/ohwgiles/laminar/pull/170

**Comment by ohwgiles** [comment]
Solved in #198
