### ISSUE TITLE
Disable proxy buffering in example nginx configuration

### ISSUE THREAD

**Issue by arunisaac** [ohwgiles/laminar#171]
Hi,

I believe proxy buffering also needs to be disabled in the nginx configuration example at `https://github.com/ohwgiles/laminar/blob/master/examples/nginx-ssl-reverse-proxy.conf`. See, for example, Mozilla's demo server-sent events app at https://github.com/mdn/dom-examples/tree/master/server-sent-events

Thanks!

**Comment by ohwgiles** [comment]
Isn't this sufficient? https://github.com/ohwgiles/laminar/blob/master/src/http.cpp#L207

**Comment by arunisaac** [comment]
I found that another way to solve the problem is to set `proxy_pass_header X-Accel-Buffering` on the inner nginx. Anyway, nothing to change in laminar.

Thanks, closing this issue now!

**Comment by arunisaac** [comment]
> Isn't this sufficient?
> https://github.com/ohwgiles/laminar/blob/master/src/http.cpp#L207

Ah, maybe I understand what's happening now! My setup involves two
layers[1] of nginx reverse proxy in front of laminar. Like this:

laminar -> nginx -> nginx -> browser

And, I had issues with SSE events going through only with these two
layers of reverse proxying. Earlier, I had only a single nginx layer,
and SSE events would go through fine without any special nginx
configuration, not even `proxy_http_version 1.1` and `proxy_set_header
Connection "1.1"`. I didn't understand why there was a problem only when
I had two layers of nginx, but what you pointed out explains it. Maybe,
the problem was the outer nginx buffering the inner nginx, and nothing
to do with laminar.

You can close this issue now. Thanks!

[1]: Unusual, I know. But, not easily avoidable with the way I am
running laminar inside a container
