### ISSUE TITLE
UI: TypeError: Chart.scaleService is undefined

### ISSUE THREAD

**Issue by centic9** [ohwgiles/laminar#175]
When installing laminar via the current Debian Testing (Version 1.1-1), the WebUI does not work and I see the following JavaScript error in the Browser-Console:

```
Uncaught TypeError: Chart.scaleService is undefined
    <anonymous> http://localhost:8080/js/app.js:377
```

The related location in app.js is

```
// For all charts, set miniumum Y to 0
Chart.scaleService.updateScaleDefaults('linear', {
    ticks: { suggestedMin: 0 }
});
```

Sounds like some incompatibility with ChartJS? Any way to avoid/fix this? 

Changes since 1.1 do not seem to contain any relevant fix.

**Comment by centic9** [comment]
Seems the build tries to include 2.7.2:

https://github.com/ohwgiles/laminar/blob/a50514a13527ba173d852e60263f6f95dff1725c/CMakeLists.txt#L90

But the Debian package replaces this with newer version:

https://sources.debian.org/src/laminar/1.1-1/debian/patches/0000-Patch-build-system-to-use-JS-libraries-from-Debian-p.patch/

Do you plan to support newer chart.js or should we report this at Debian?

**Comment by centic9** [comment]
See https://www.chartjs.org/docs/latest/getting-started/v3-migration.html for migration steps for Chart.js to 3.x, it mentions "scaleService": 

`Chart.scaleService was replaced with Chart.registry. Scale defaults are now in Chart.defaults.scales[type].`

**Comment by ohwgiles** [comment]
Thanks for this. I should support the newer ChartJS, but the API has changed significantly so the porting is not trivial.

Incidentally, Vue has also advanced significantly since the version used here, but Debian haven't updated it yet. So a similar (probably worse) issue will happen when that happens.

**Comment by centic9** [comment]
FYI for anybody running into this, I worked around it via a custom Debian package at https://launchpad.net/~dominik-stadler/+archive/ubuntu/ppa/+packages which does not replace the bundled libraries for now until this is fixed.

**Comment by ohwgiles** [comment]
I also make official releases as Debian packages which have fixed versions of these dependencies. See [the releases page](https://github.com/ohwgiles/laminar/releases).

**Comment by jeromebrunet** [comment]
Hi,

Sorry for posting on a closed topic.
I've also run into the issue just before the package got dropped from debian testing, which seems to have happened today.

I tried installing the package from the laminar webpage.
It does not work on trixie because of libcapnp

```
The following packages have unmet dependencies:
 laminar : Depends: libcapnp-0.7.0 but it is not installable
```

At the moment, trixie provides `libcapnp-1.0.1`
Manually installing libcapnp-0.7.0 from the bullseye repo seem to work though.

**Comment by ohwgiles** [comment]
> package got dropped from debian testing, which seems to have happened today

Thanks for the notification, I'll see what I can do here

> I tried installing the package from the laminar webpage.

Those are for Debian 11 (bullseye), trixie is 13, I would expect this kind of error.

**Comment by jeromebrunet** [comment]
> Those are for Debian 11 (bullseye), trixie is 13, I would expect this kind of error.

No worries, I was not expecting compatibility with testing from this package.
The only problem was `libcapnp`. I don't know anything about it to be honest. Do you think it would be compatible with version `1.0` ? 

It's likely to be necessary to get back in debian testing I suppose.
