### ISSUE TITLE
Double encoding of HTML in job output

### ISSUE THREAD

**Issue by ehuelsmann** [ohwgiles/laminar#176]
In the logs of my jobs (on laminar 1.0.3), I'm seeing

`virt-resize --help &gt;/dev/null 2&gt;&1`

As you can see, the `<` and `>` get double-encoded, but `&` doesn't.

While I know 1.0.3 is old, I missed this fix in the release notes.

**Comment by ohwgiles** [comment]
Does not reproduce on current version
