### ISSUE TITLE
Make jobs next run number immutable to crash

### ISSUE THREAD

**Issue by palica** [ohwgiles/laminar#18]
Hi Oliver,

so I have laminar crashing upon me under load. And if I restart it there are stale run directories, which don't allow to start new runs or jobs. 

It would be good to solve the crashing problem of course, but also if a crash happens enable laminar to recover from it: 

- deleting stale directories in ~laminar/run/job_name/
or
- mark the last run number in the database so the new jobs get the next higher run number

Let me know what you think.

Pavol

**Comment by palica** [comment]
After I restart laminard after a crash there are no finished jobs, so the new jobs get added to the queue, but never start executing, because of this:
```
laminar.cpp:582: error: Could not create working directory; rd.string() = /var/lib/laminar/run/fun-prime/1
```

If I delete the ~laminar/run/1 directory then I am getting this:
```
laminar.cpp:590: warning: Archive directory already exists; archive.string() = /var/lib/laminar/archive/fun-prime/1
```

**Comment by ohwgiles** [comment]
Instead of deleting stale directories or forcing a database entry when a job is started rather than completed, how about I just output a warning and continue if the directory already exists? It is anyway a case that should never happen so I prefer not to put too much logic into it

**Comment by palica** [comment]
Or clean up the run dir. Delete it maybe.

**Comment by ohwgiles** [comment]
New behaviour attempts to delete an existing run dir, but will continue anyway if that fails
