### ISSUE TITLE
FE: "Jobs" link not working with new-and-not-yet-built jobs

### ISSUE THREAD

**Issue by jbglaw** [ohwgiles/laminar#189]
Hi!

It seems that you cannot use the grouped "Jobs" view when there are jobs that don't (yet) have had a "run". This results in an error message like this:
```
ReferenceError: j is not defined
    at app.js:490:32
    at Array.forEach (<anonymous>)
    at a.status (app.js:484:21)
    at a.<anonymous> (app.js:828:37)
    at Array.<anonymous> (vue.min.js:6:12466)
    at qe (vue.min.js:6:11867)
```

**Comment by jbglaw** [comment]
Just for reference: The `j is not defined` is the unshift for the special case of the first run. I guess the first is (correctly) special-cased, but it's failing when there is no run at all for a given job.

**Comment by ohwgiles** [comment]
I can't reproduce this on the current master. Can you provide more detailed instructions please.

**Comment by jbglaw** [comment]
Please try like this:

* Add a few new jobs (ie. foo1.run, foo2.run), but don't queue them yet!
* Create a new entry in groups.conf (Foo=^foo)
* Open Laminar FE in browser
* In the dark row at the top, click on the "Jobs" (right of the instance name)
* --> Error in Browser's JS console
* Queue the "foo*" jobs
* Open FE again in Browser, navigate to the "Jobs" link.
* --> Grouped jobs (as per groups.conf) are shown.
I'm currently having some long-running jobs, along with some new (never queued) jobs, so my current setup shows the behavior: http://toolchain.lug-owl.de/laminar/jobs is quite empty (due to the JS issue), while you see them at the regular start page (http://toolchain.lug-owl.de/laminar/).

**Comment by jbglaw** [comment]
The crosstoolng-* jobs are the new ones, having their very first runs right now (one by one, next to the more hefty NetBSD builds.)

**Comment by jbglaw** [comment]
The (updated) Debian package didn't yet have upstream commit e7defa9f15b8fac9716246978b1714725017cc81. That's the actual fix.
