### ISSUE TITLE
[feature request] Abort button. 

### ISSUE THREAD

**Issue by nicolas-graves** [ohwgiles/laminar#199]
In the web UI, having an abort button on a job might be useful.

**Comment by ohwgiles** [comment]
Laminar is explicitly designed such that the UI is read-only. Among other reasons, this avoids the need to implement user roles/privileges.

You can quite easily add this feature to your local installation using a simple CGI shell script behind your reverse proxy and modifying the frontend using a [custom HTML template](https://laminar.ohwg.net/docs.html#Customizing-the-WebUI).
