### ISSUE TITLE
No logs in Web UI

### ISSUE THREAD

**Issue by kisik21** [ohwgiles/laminar#2]
Trying to grasp laminar's power, but something went wrong... I queued a "hello" job, tried to run it 5 times, and received no log output, when I looked into Web UI!

Tried to run it 6th time, received some log output while the job is still running, but after reloading, the job is shown like it never was - everything is NaN or undefined, and no logs are saved.

Maybe it's a bug, maybe it's intentional, but how to make laminar at least save the job logs and stats? By the way, the "Last success" and "Last build" stats on job screen also suffer from this.

**Comment by ohwgiles** [comment]
It definitely sounds like something's wrong there, all logs and stats should be saved.

Laminar stores these in an sqlite database `laminar.sqlite` under `$LAMINAR_HOME` (which is `/var/lib/laminar` by default).

Is there any output from `laminard` in the console (or in systemd journal if you run it from there)? Maybe laminar failed to create this file? Or its permissions are wrong?

**Comment by kisik21** [comment]
Yes, permissions problem. I accidentally launched `laminard` as root, this made the sqlite database with root perms.
