### ISSUE TITLE
[PROPOSAL] Manual triggers

### ISSUE THREAD

**Issue by mapperr** [ohwgiles/laminar#201]
Hi everyone,

I was thinking about functionalities I'm possibly missing from other CI servers, and one thing that comes to mind are manual triggers.

## What is the use case?

The simplest I have in mind is:

- Bob is working on a codebase
- The application built from the codebase can be deployed in a TEST and a PROD environment
- for the codebase we have 2 jobs: `build_codebase_job` and `deploy_application_job`
- `deploy_application_job` job is parametrized (i.e. it takes a `env=TEST` or `env=PROD` parameter)
- Bob pushes some changes (commits on a branch, a tag, whatever)
- the `build_codebase_job` job is triggered from the push (is some way, doesn't matter)

now, instead of deploying automatically base on conditions (branch, tag, or else) or give ssh access to Bob and tell him how to trigger the `deploy_application_job` job,  
I could make Laminar send Bob an email with 2 links.  
Those links can trigger the `deploy_application_job` job, each with its parameters already set (one with env=TEST and one with env=PROD).

## How can it work

I was thinking about a  

`laminarc prepare <job_name> [param1=val1 [param2=val2] ... ]`  

with the same format of the other `queue`, `start` and `run` commands.

`prepare` (or some other verb to our liking) does not queue the job, it saves it into the db and it generates a `trigger_id` (or some other name to our liking),  
that is a uuid or something unique that can be also used in an url.
The output of this command can be the `trigger_id` (or `$JOB:$TRIGGER_ID`) instead of the `$JOB:$RUN` of the other sibling commands (queue, start, run).

The prepared job can be aborted like any other job.

On `https://<laminar_addr>/$JOB/$TRIGGER_ID` we can see a page with the prepared job infos and we can click something to actually queue the job.

(I don't know if this can align with the beautiful minimal philosophy of Laminar: there will actually be a 'queue' action via the web UI.)

---

The general use case is to setup a job call and give an anonymous user the ability to queue it.

Makes sense to you?

**Comment by ohwgiles** [comment]
Generally I want the web UI to remain read-only, even for "prepared" jobs, for reasons [explained](https://github.com/ohwgiles/laminar/blob/master/UserManual.md#isnt-there-a-build-now-button-i-can-click) [several](https://github.com/ohwgiles/laminar/issues/109) [times](https://github.com/ohwgiles/laminar/issues/199).

I understand your point about "preparing" a job, but I don't think that is a good fit for a built-in laminar feature. The second of the above links might provide a good starting point for implementing this. Perhaps your `build_codebase_job` would create some files/tokens/dbentries (you could make another table in `laminar.sqlite` if you like) and send an email, then your reverse proxy would provide the `$TRIGGER_ID` endpoint to a one-line script that actually calls `laminarc queue` as per usual.

**Comment by mapperr** [comment]
Ok, I think I get the general direction now: considering the huge flexibility of Laminar, we can keep it a solid base and work on examples to give ideas on how to implement use cases like this.

Thanks!
