### ISSUE TITLE
LAMINAR_KEEP_RUNDIR should keep the <n> most recent job runs

### ISSUE THREAD

**Issue by seifertm** [ohwgiles/laminar#22]
The current behaviour of ``LAMINAR_KEEP_RUNDIR`` is that if the env variable is set, all job runs will be preserved. This leads to jobs piling up on the disk, which is why this setting is disabled in my setup. However, if I need to inspect the environment of a failed job, I have to change the configuration, restart laminar, and re-run the failing job.

I suggest that ``LAMINAR_KEEP_RUNDIR`` supports integer values. The integer represents the number of run directories that will be preserved.
For example: ``LAMINAR_KEEP_RUNDIR=3`` will preserve the three most recent run directories for every job.

This would allow me to enable the setting permanently. It would be easier to inspect and debug the environment in which a job failed without having to re-configure and restart laminar.

I am bringing this idea up, because it seems somewhat related to #18 .

**Comment by ohwgiles** [comment]
On its own this would not help solve #18, but it's anyway a reasonable idea

**Comment by ohwgiles** [comment]
As you currently describe it, there would be no way to keep **all** of the run dirs. Which actually I quite like :)

**Comment by ohwgiles** [comment]
This is a bit trickier than it sounds. Currently, when a run ends it cleans up its own rundir. Laminar allows you run multiple runs of the same job simultaneously (maybe with different parameters), and there's no reason why higher numbered runs couldn't finish before lower numbered runs. If they were to take care of deleting older rundirs, they could easily delete a directory for a run that is still in progress. So this rule would have to be something more like "keep X number of rundirs behind the oldest currently running execution of a job"

**Comment by seifertm** [comment]
I can see use cases where you want to keep all run directories, e.g. for keeping log files of job runs.
What do you think of the special case `LAMINAR_KEEP_RUNDIR=*` for keeping all run dirs?

**Comment by ohwgiles** [comment]
I think I'd argue that if you really want to keep anything "forever", you should move it to the `$ARCHIVE` directory

**Comment by ohwgiles** [comment]
I've pushed a commit that implements this, your feedback would be much appreciated. Please note that I have also changed `LAMINAR_KEEP_RUNDIR` to `LAMINAR_KEEP_RUNDIRS`

**Comment by seifertm** [comment]
For me, everything works as expected and it perfectly fits my use case.
This is great, thank you! :)
