### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by MarcCoquand** [ohwgiles/laminar#223]
Hello!

Just a heads up, it seems the website is down. I can't access it.

**Comment by ohwgiles** [comment]
Fixed thanks

**Comment by metaspace** [comment]
Still down for me: `Error code: PR_CONNECT_RESET_ERROR`

**Comment by metaspace** [comment]
I am mostly using the website for the documentation. Is it possible to build the documentation locally? I browsed the source, but did not come across anything looking like docs.

**Comment by MarcCoquand** [comment]
You can access it from archive.org for now while waiting for it to be up
again

https://web.archive.org/web/20240301114443/http://laminar.ohwg.net/docs.html#Defining-a-job

--

**Comment by ferki** [comment]
> Is it possible to build the documentation locally? I browsed the source, but did not come across anything looking like docs.

@metaspace: The website content apparently comes directly from the [UserManual.md](https://github.com/ohwgiles/laminar/blob/9da39ed3f7ec083af2c40428db3b100475f087c0/UserManual.md) file.

**Comment by ohwgiles** [comment]
Back up again, I'll consider moving to a more stable host in the future.

> Is it possible to build the documentation locally?

As @ferki mentioned, the documentation is just generated from UserManual.md. I use

`theme -c +toc,+idanchor < ./UserManual.md > docs.html`

`theme` is part of the standard "discount" markdown package, using [this template](https://github.com/user-attachments/files/18103971/page.theme.txt)

**Comment by MarcCoquand** [comment]
Seems it's down again :(

-- 
Marc
