### ISSUE TITLE
Strange time counter

### ISSUE THREAD

**Issue by kisik21** [ohwgiles/laminar#28]
When starting a job, amount of time passed starts on negative value. Looks very strange.

Also, how is estimate progress calculated? Maybe this is connected.

**Comment by ohwgiles** [comment]
I don't see this currently. Can you describe exactly how to reproduce it?

The estimated time is just the time that the last run took (search for "etc" - estimated time of completion, in `laminar.cpp`). The bar goes orange if the run has taken more than 120% of this time (`app.js:110`)

**Comment by ohwgiles** [comment]
Could it be that the time on your server and client are not in sync? I think that could cause this behaviour

**Comment by ohwgiles** [comment]
Can you confirm that this is caused by mismatched system clocks? If that's the case I can probably add a workaround to make the counters look normal

**Comment by kisik21** [comment]
'Tis the clock. Suggestion: Make a time check on the server, send it to
client and then calculate time skew.

**Comment by ohwgiles** [comment]
Yep that's what I was thinking. Hopefully I'll get around to it this weekend
