### ISSUE TITLE
laminard crashing in hardened gentoo with: terminate called after throwing an instance of 'kj::ExceptionImpl'

### ISSUE THREAD

**Issue by palica** [ohwgiles/laminar#31]
Hi Oliver,

it is me again. 

I am getting this on my box, again: 

```
terminate called after throwing an instance of 'kj::ExceptionImpl'
  what():  kj/async-io-unix.c++:297: disconnected: ::read(fd, buffer, maxBytes): Connection reset by peer
stack: 0x7f7ca9133236 0x7f7ca91093f4 0x4456c0 0x42fb0c 0x7f7ca911076d 0x7f7ca9108ea9 0x7f7ca910ceb4 0x4338ba 0x42c08c 0x458274 0x42a157 0x7f7ca79e672c 0x42a368
```

What info do you need to debug?

**Comment by ohwgiles** [comment]
Hi Pavol,
Can you reproduce this easily? Does it happen only when a job is running? Does it only happen when the web UI is open?

**Comment by palica** [comment]
Don't know if I can reproduce it easily, I was running a batch job where I call one run script with variable and running tens of jobs. The web ui was open. And it happened during this batch of jobs.

**Comment by palica** [comment]
```
terminate called after throwing an instance of 'kj::ExceptionImpl'
  what():  kj/async-io-unix.c++:139: overloaded: ::write(fd, buffer, size): Connection timed out
stack: 0x43d871 0x45636f 0x7fee07e993f4 0x42fb0c 0x7fee07ea076d 0x7fee07e98ea9 0x7fee07e9ceb4 0x4338ba 0x42c08c 0x458274 0x42a157 0x7fee0677672c 0x42a368

```
so yes overnight same problem, web ui running, notifiation enabled in browser. while running jobs.

**Comment by palica** [comment]
running latest commit ae961b97cb55e9151e48c83179b7af0b4e6e0eb2

**Comment by ohwgiles** [comment]
I think I know what this is. Working on a fix. In the meantime, any chance you can confirm my suspicions that it does not happen if the web ui is not open?

**Comment by palica** [comment]
I am going to test it without web ui open. I will post results probably in the morning. I'll let it run overnight.

Thank you for looking into it!

**Comment by palica** [comment]
Overnight jobs running without laminar crashing (no web ui open).

**Comment by ohwgiles** [comment]
The latest commit should resolve this properly, thanks for your help
