### ISSUE TITLE
ENV=whatever laminarc trigger jobname not the same as laminarc trigger jobname ENV=whatever ; expected?

### ISSUE THREAD

**Issue by palica** [ohwgiles/laminar#35]
Is this expected behaviour? 

If I run the command with ENV=env laminarc trigger job the ENV doesn't get passed to the job, but if I do laminarc trigger jobs ENV=env - env gets passed to the job.

**Comment by ohwgiles** [comment]
In the first method, bash sets the environment variable and calls `laminarc`. In the second, `laminarc` parses the extra arguments as `argv`.

This is by design. We can argue whether it’s a sensible design, but yes this is the expected behaviour.

**Comment by palica** [comment]
ok, thanks for clarifying.
