### ISSUE TITLE
display or load more jobs when scrolling down on the /jobs/ page

### ISSUE THREAD

**Issue by palica** [ohwgiles/laminar#38]
So currently if you stay on the jobs page and let jobs run, you are able to see all jobs that started after you have opened the jobs page. If you follow a link to details about single job and come back you only see approx 30 jobs. 

It would be nice if you scroll to the bottom of the page that the page would dynamically load more finished jobs (it can be 30 at a time).

Do you know what I am trying to say?

**Comment by ohwgiles** [comment]
You are right that there is currently no way to see older jobs on the jobs page. What you are describing is called "infinite scrolling" and it's a pattern used on content-heavy websites to keep the user engaged. If the user is searching for something specific, as I think is relevant in this case, usually pagination is preferred. Would next/previous page buttons solve this issue for you?

**Comment by palica** [comment]
yes, I would be happy with next previous buttons :)

**Comment by ohwgiles** [comment]
@palica does this implementation work for you?

**Comment by palica** [comment]
yes, I am happy with this.

[Page with listing on my instance](http://laminar.liguros.net/jobs/fun-prime)

**Comment by palica** [comment]
OK, but I have a new bug related to this. Should I open a new issue or just continue here?
