### ISSUE TITLE
sort runs by result, or any other field

### ISSUE THREAD

**Issue by palica** [ohwgiles/laminar#40]
would it be possible to sort the runs by result (success,failure), date started, duration, reason ....?

what are you thoughts on this, please.

**Comment by ohwgiles** [comment]
This is possible, it could be done client or server side. The problem with doing it server side means a lot of extra logic on the server, the problem with client side is that it would require fetching the entire history of a job. It's closely related to #38. It's a reasonable request but probably I will not have time for it in the short term

**Comment by palica** [comment]
that is ok, I can wait. thanks for considering.

**Comment by ohwgiles** [comment]
Hi @palica, please see if this adequately implements your request

**Comment by palica** [comment]
could I get an average line for the build time in the graph, please?
