### ISSUE TITLE
Badge url

### ISSUE THREAD

**Issue by ohwgiles** [ohwgiles/laminar#50]
A job's current status could be served as a badge, e.g. `laminar:8080/jobs/JOB/badge.svg`. Remember to set a short cache period.

**Comment by ohwgiles** [comment]
Probably better to be implemented with a helper script as an artifact

**Comment by ohwgiles** [comment]
Changed my mind again. I don't want to fill up artifact directories with redundant copies of the same svg file

**Comment by transferkraM** [comment]
Hey guys,

(hate to comment on a clodes issue, anyway, )

I've b15166e8 installed, which should contain 132d40e6. GET on ...`/badge/<jobname>.svg` returns 404. Anything I missed here? From reading the code, I guess, that URL should work?

**Comment by ohwgiles** [comment]
Hi, thanks for spotting this - it was a recent regression in cec4721e. Now fixed with bb81931.

**Comment by transferkraM** [comment]
Great, updated to bb81931, badge url is now working properly. Thank you!
