### ISSUE TITLE
laminard has executable stack

### ISSUE THREAD

**Issue by lachs0r** [ohwgiles/laminar#55]
When packaging Laminar, I got this warning from rpmlint:

```
laminar.x86_64: W: executable-stack /usr/sbin/laminard
The binary declares the stack as executable.  Executable stack is usually an
error as it is only needed if the code contains GCC trampolines or similar
constructs which uses code on the stack.  One common source for needlessly
executable stack cases are object files built from assembler files which don't
define a proper .note.GNU-stack section.
```

That’s a CVE waiting to happen, so it should be fixed.

**Comment by ohwgiles** [comment]
Thanks for spotting this. It's fixed in master now, but the next release is probably several months away. Until then, if you want to package version 0.6 you could consider applying b1dc0d6 as a patch or adding `-Wl,-z,noexecstack` to your `LDFLAGS`
