### ISSUE TITLE
WebUI design refresh

### ISSUE THREAD

**Issue by ohwgiles** [ohwgiles/laminar#57]
The current Bootstrap 3 layout is starting to look a bit dated

**Comment by cweagans** [comment]
How do you feel about Semantic UI? I was thinking about tackling this this weekend.

**Comment by ohwgiles** [comment]
Never used it, no idea. I don't want to complicate the build process, or introduce dependencies which might complicate packaging for downstream distributions. Actually I was thinking of tackling this with no libraries at all, but if Semantic makes this easier without the aforementioned issues then I'm not opposed...

**Comment by cweagans** [comment]
Progress:

![image](https://user-images.githubusercontent.com/101590/75755368-b4496400-5ceb-11ea-85ae-4cbca6b6abdd.png)

So far, it's just the status page, but that seemed to be the most complicated page. I think I can get the remaining routes finished up tomorrow if you'd like me to continue on this.

**Comment by cweagans** [comment]
Also, the JS libraries are served directly from jsdelivr so there won't be any packaging issues for downstream distributions. This is the relevant block from index.html:

```
<script src="https://cdn.jsdelivr.net/npm/vue@2.6.11/dist/vue.min.js" integrity="sha256-ngFW3UnAN0Tnm76mDuu7uUtYEcG3G5H1+zioJw3t+68=" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/vue-router@3.1.6/dist/vue-router.min.js" integrity="sha256-B8zvQ+y1lIQkcm+EJyCis+7AgsnzaTCBAHgkrPFQr9A=" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/ansi_up@1.3.0/ansi_up.js" integrity="sha256-2UR0QYPMTIY0yP5S6ubBS7wFNKhn8uW7pV5E3LlvI6U=" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js" integrity="sha256-R4pqcOYV8lt7snxMQO/HSbVCFRPMdrhAFMH+vr9giYI=" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/semantic-ui@2.4.2/dist/semantic.min.css" integrity="sha256-UXesixbeLkB/UYxVTzuj/gg3+LMzgwAmg3zD+C4ZASQ=" crossorigin="anonymous">
```

**Comment by ohwgiles** [comment]
> Progress

While perhaps a step up from the current design, to me it looks a bit like CircleCI, which also feels a bit dated. Perhaps it's that style of card widget which has already become less prevalent recently.

I'm not a UX person but the enable/disable notifications button surely shouldn't be the same size/shape as other navigation buttons?

> JS libraries are served directly from jsdelivr

Sorry, this is a no-go. Privacy-focused users and distributions rightly won't accept that a CDN tracks their use of a self-hosted service, which will likely be run on a private network. Laminar frontend shouldn't be dependent on the wider internet. I just checked, and it looks like Debian [doesn't have a package for Semantic UI yet](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=915062). In fact, this is preventing gogs from getting into Debian. So I think Semantic UI can't be used unfortunately.

----

Sorry if this comes off a little negative, I do really appreciate the effort :thumbsup:

**Comment by cweagans** [comment]
> While perhaps a step up from the current design, to me it looks a bit like CircleCI, which also feels a bit dated. Perhaps it's that style of card widget which has already become less prevalent recently.

Are you talking about the graphs section on the right? I'm not a big fan of that either, but that was the easy thing to do just to get it working. I'd be happy to look into other options if needed.

> I'm not a UX person but the enable/disable notifications button surely shouldn't be the same size/shape as other navigation buttons?

Probably not. That bit is WIP.

>  Privacy-focused users and distributions rightly won't accept that a CDN tracks their use of a self-hosted service, which will likely be run on a private network

I'm definitely not married to the idea of jsdelivr. I figured it'd be way easier to do that than to package it for Debian though.

> I just checked, and it looks like Debian doesn't have a package for Semantic UI yet. In fact, this is preventing gogs from getting into Debian. So I think Semantic UI can't be used unfortunately.

IMO: the upstream distro packaging process is a nightmare and should be avoided at all costs. It's just not worth the hassle to worry about which version your users are running, whether or not they're able to upgrade, etc. I went through this process with [Universal Ctags](https://github.com/universal-ctags/) and it continues to be terrible. Another path forward would be to use https://build.opensuse.org/ , which will build packages for multiple distros and host them for you. I'd be happy to do the legwork on this if you want to use a service like that.

**Comment by cweagans** [comment]
I went ahead and finished this up, so here's a few more screenshots for future consideration:

![image](https://user-images.githubusercontent.com/101590/75828727-bfdb7000-5d69-11ea-924f-563185689f12.png)

![image](https://user-images.githubusercontent.com/101590/75828742-c833ab00-5d69-11ea-8801-e7d6eda5d5d7.png)

![image](https://user-images.githubusercontent.com/101590/75828754-cec22280-5d69-11ea-9729-ea677e705c1d.png)

**Comment by ohwgiles** [comment]
Nice work. I'm sorry it can't go in as it is, but it will be a source of inspiration to the eventual solution.

> IMO: the upstream distro packaging process is a nightmare and should be avoided at all costs

Carefully curated official repositories are an important indicator of quality and trust. So I guess we'll agree to disagree on this point. In saying that, I do make binary packages for Debian/Ubuntu and CentOS (available on the releases page). I'm not averse to offloading that work to OBS, but I haven't used that before and I'm not sure how much value it would add for end users over my manually built packages.

**Comment by cweagans** [comment]
OBS hosts a repo for you as well, so future updates are a matter of `apt upgrade laminar` (or whatever the dnf command is now), as opposed to downloading the new package and manually installing it. It's a small gain if you're already committed to getting laminar into the official repos though.

**Comment by ohwgiles** [comment]
Ok thanks. I think I'll stick with the current approach for now, but I might reconsider if it turns out too problematic

**Comment by cweagans** [comment]
:+1:
