### ISSUE TITLE
Mutual exclusion (enhancement?)

### ISSUE THREAD

**Issue by Warbo** [ohwgiles/laminar#60]
Laminar looks really nice, and I'm currently migrating over to it. One scenario that would be nice to support (although it's not possible on my old CI system either) is allowing some jobs to be run with exclusive access to a node, i.e. without any other job running concurrently. This would be useful for running benchmarks, where we don't want anything else intensive to be running on the same machine.

I can see two ways to do this with Laminar: setting a node's executors to 1, or having all jobs aquire/release a lock. Either way, this would cause *all* jobs to be run one at a time, which would be frustrating when there are no queued benchmarks but lots of normal jobs. We could also implement this by shutting down one laminar service, bringing up another to perform benchmarks, then switch back, but I'm not sure how easy that would be. If there are any other ways to implement this, I'd love to know!

I can think of a few possible alterations to Laminar that would allow *some* jobs to get exclusive access:

 - Jobs could specify that they want exclusive access to their node. This would be some boolean option on the job, defaulting to false.
 - More generically, jobs could specify that they need a certain number of executors. For example, the default node has 6 executors. If benchmark jobs specify that they need 6 executors, they would get exclusive access to that node. Jobs would default to needing 1 executor, which allows 6 to run concurrently. This would also allow combinations like 2 3-executor jobs running concurrently, 2 2-executor jobs + 2 1-executor jobs, etc. This might be useful as a more fine-grained approach than the 'CPU intensive' example from the documentation, but I'm not sure if the extra complication would be worth it or not. I certainly don't have a compelling use-case besides benchmarking exclusivity, and even that would require coordinating the configuration of the nodes and the jobs in this implementation (the executor count of the node and benchmark job would need to be kept in sync to maintain exclusivity).
 - The locking mechanism could be extended from just a mutex to an increment/decrement semaphore. However, this feels like a poor man's reimplemention of the existing executors functionality.

Some care might also have to be taken w.r.t. job scheduling. When an exclusive/multi-executor job is next in the queue, we could do a few things:

 - The simplest approach would be to wait until enough executors become available before we pop it off. This has the downside that many executors may be sit idle while we wait for a long-running job to free the last executor, with a backlog of quick single-executor jobs building up behind the benchmark.
 - An alternative is to look further into the queue for jobs which are able to run with however many executors are currently free. This has the downside that we may never end up running the benchmark, since it's waiting for the Ship of Theseus to rot.

Personally I prefer the simplicity of the first approach.

I like Laminar's lightweight nature, and I wouldn't want to bloat it with features. So it's fine if this doesn't get implemented. I'm just throwing it out as an idea that would be useful (and on the off chance that there's a better way to do this I hadn't thought of!)

**Comment by singpolyma** [comment]
If the locks were extended to read/write locks, then you could do `laminarc lock --read $NODE` in the `$NODE.before` and `laminarc lock $NODE` in only jobs that need exclusive access.

**Comment by singpolyma** [comment]
In fact, you could do this without laminar help.  You could use `flock -s /some/path/$NODE -c /actual/script` in everything that doesn't need exclusive access and `flock /some/path/$NODE -c /actual/script` when exclusive is needed

**Comment by Warbo** [comment]
@singpolyma Nice idea, I'll give this a try! In my current laminar setup I'm generating the `cfg` directory programatically using Nix, so it's easy to add boilerplate like this to all jobs; plus I can add a test to check that all job scripts are calling `flock` (i.e. when I inevitably forget to add it to a new job!).

**Comment by ohwgiles** [comment]
Ah, I had forgotten about `flock`. Since one of laminar's main design goals is not reinventing the wheel, I think I'll remove locks from the next release, unless anyone knows a reason to keep them?

**Comment by ohwgiles** [comment]
Of course, the downside with locks (whether `flock` or laminar locks) is that the job run time stats are no longer necessarily a reliable indicator of the actual time spent executing. Dynamically modifying the number of executors avoids this problem. If this is actually useful it could be made cleaner...

**Comment by Warbo** [comment]
@ohwgiles That's true, but personally I don't mind the times being unrepresentative. They're nice to have, but it's a sacrifice I'm willing to make for my (perhaps niche) use case. In particular:

 - My benchmarks do their own timing
 - I don't care too much about times of non-benchmark jobs (for those using Nix, it's basically a question of whether they hit/miss the cache; and that's already written to their stderr)
 - If I end up wanting times for e.g. reporting I would probably use something like `ts` from moreutils to get more fine-grained information (e.g. to see which step, tests, etc. are the slowest)

**Comment by ohwgiles** [comment]
Seems like this issue has been adequately worked-around :)
