### ISSUE TITLE
Hints on how to quickly install `rapidjson` on those distributions that don't feature it

### ISSUE THREAD

**Issue by cipriancraciun** [ohwgiles/laminar#74]
I've tried to build `laminar` on OpenSUSE Tumbleweed (i.e. the "rolling" release of OpenSUSE, with all the latest packages), and unfortunately there is no `rapidjson` package (neither official or unofficial).

However it seems that installing `rapidjson` is not needed as long as the user just copies the folder `include/rapidjson` directly into the worktree of `laminar`. I.e.:

````
git clone https://github.com/Tencent/rapidjson
cp -r ./rapidjson/include/rapidjson ./laminar/rapidjson
````

(I know this is mostly a "hack", but I wanted to build it quickly.)

---

BTW, on OpenSUSE the following are the development dependencies needed:
```
capnproto
libcapnp-devel
sqlite3-devel
libboost_container1_68_0-devel
```

**Comment by ohwgiles** [comment]
Thanks for pointing this out. Some searching led me to [this](https://build.opensuse.org/repositories/devel:libraries:c_c++/rapidjson) but I don't know anything about openSUSE so it could be irrelevant. If there is a standardised way of submitting user packages (like the AUR for Arch Linux), it would be great to be able to share laminar with other openSUSE users.

**Comment by cipriancraciun** [comment]
The following link provides available packages from OpenSUSE build service for `rapidjson`:  https://software.opensuse.org/package/rapidjson

However as seen only "source" packages are available for OpenSUSE.  (At least at this moment.)

Providing OpenSUSE packages is done via https://build.opensuse.org/, which also handles the building.

**Comment by cipriancraciun** [comment]
> Rapidjson is a header-only library, so the sources are all that are needed, and only for compilation.

Yes, I understand.  However the "sources-only" RPM packages (i.e. `*.src.rpm`) are not installable, and are in fact a bundle destined for the `rpmbuild` tool.

**Comment by ohwgiles** [comment]
Ah, ok. So  if laminar sometime becomes an openSUSE rpm, all its dependencies including rapidjson would be available, right? I don't know how compatible their rpm implementations are, but I have a quick-and-dirty way to [generate a rpm for centos](https://github.com/ohwgiles/laminar/blob/fda11a652b4058105af34d56f5c37e922711ab77/docker-build-centos.sh#L42) that could be a useful starting point

**Comment by cipriancraciun** [comment]
> Ah, ok. So if laminar sometime becomes an openSUSE rpm, all its dependencies including rapidjson would be available, right?

In case of `rapidjson` it is not needed to be present for "install".  (Only for "building", and this is why I contributed this "build hint" issue.)

Thus the unavailability of an `rapidjson` RPM is not an issue for the "user", just for the "builder".


> I don't know how compatible their rpm implementations are, but I have a quick-and-dirty way to [generate a rpm for centos](https://github.com/ohwgiles/laminar/blob/fda11a652b4058105af34d56f5c37e922711ab77/docker-build-centos.sh#L42) that could be a useful starting point

I'll take a look.  They should be almost compatible, most likely only dependencies are changed.

**Comment by ohwgiles** [comment]
Cool, thanks :+1:

**Comment by ohwgiles** [comment]
I think this issue can be closed. It is still searchable for those looking for this information.
