### ISSUE TITLE
Unknown command lock

### ISSUE THREAD

**Issue by sbrl** [ohwgiles/laminar#81]
The official documentation has a [section on locks](https://laminar.ohwg.net/docs.html#Locks).

Now that I've got the link between the box my git server runs on and the box my Laminar CI server is running on sorted (I've `autossh`ed the Laminar RPC binding from one to the other), I've turned my attention to getting my CI server properly set up for all the various little projects I've got going on that could really use it.

I've got to the point where the `locks` feature I've linked to above would be really useful, but if I try to acquire a lock, I get this:

```bash
$ laminarc lock testlock
Unknown command lock
```

Hitting the `<tab>` key yields that the following commands are supported:

```
abort         run           show-jobs     show-running  
queue         set          show-queued   start  
```

Has the locks feature been removed? I'm confused.

I'm using the binaries you provided in #73.

**Comment by ohwgiles** [comment]
Yes, locks have been removed. Sorry for the confusion. You can find some of the reasoning and implementation at #63.

The official release (version 0.6) doesn't yet have that change, and my policy is that the online documentation should reflect the state of the latest official release. The binaries I built in #73 were from the master branch at the time (labelled 0.6-46).

Generally, locks can be avoided with careful tag/executor structure, with the added advantage that the job's run time actually represents the amount of time spent running (and not, for example, waiting on a lock). If there's no way around it, `flock` is recommended, as mentioned in #63.

**Comment by sbrl** [comment]
I see. Thanks for the clarification! Perhaps it would be good to do an intermediate release in which the feature is deprecated to let people know?

My use case is that I've got a number of small projects in different repositories, and I don't want to have to write a new laminar job for each one, in which I'd duplicate quite a lot of code (clone the repo, execute the build script, etc.). Rather, I'd like to keep the build script for a project inside it's repository, and have a simple process to hook a new project up to my CI server.

To this end, I've written a job that clones itself via a symbolic link to be the name of the repository and then calls the symlink. Then, it clones the repository (given in an environment variable), checks out the right commit (also given in an env variable), `cp -ral`s the contents to the run directory from the workspace, locates the build script (I've developed my own [bash-based build system](https://gitlab.com/sbrl/lantern-build-engine), and executes it.

It is for this reason that I'd like to use a lock on the git repository while I check out and `cp -ral` the contents to the run directory, just in case I push multiple commits too quickly.

**Comment by sbrl** [comment]
Also, I'm really confused by executors and tags, and I don't understand the explanation in the documentation.

**Comment by ohwgiles** [comment]
In the future I think such visible changes will be done more carefully, yes. Hopefully I will get around to making a new release quite soon and we can put all this behind us ;)

Regarding your specific issue, this is basically the case that is described in the user manual. It was updated when the locks were removed to show the example using flock - take a look [here](https://github.com/ohwgiles/laminar/blob/master/UserManual.md#data-sharing-and-workspaces). When the release is ready, the main website docs get regenerated from that markdown.

Regarding executors and tags, I agree they're not so intuitive and I hope this will be restructured in subsequent releases - I'm just not quite sure how yet. I already mentioned this in #68 and #46. Suggestions welcome...

**Comment by sbrl** [comment]
Thanks! I see. I'll investigate refactoring my job to use `flock` and see how I get on.

If I understood how they currently worked, I'd be able to make a suggestion as to how they might work better :P Here's my current understanding:

 - Every job can have 1 or more tags
 - Executors are defined globally in a configuration file, optionally with one or more tags
 - Executors take on jobs that they are compatible with, limiting the number of jobs that can be executed at once
 - An executor with one or more tags ensures that it has all the tags of a job that needs running before accepting it
 - An executor with no tags will run any job

**Comment by ohwgiles** [comment]
Almost right. The terminology I use is a bit different. If you replace "executor" with "node" most of your understanding is correct - the difference is that each node may have X executors, i.e. the ability to run X matching jobs in parallel.

> An executor with one or more tags ensures that it has all the tags of a job that needs running before accepting it

No, it just needs a single matching tag.

The implementation can be simply seen in the [nodeCanQueue function](https://github.com/ohwgiles/laminar/blob/31c64980f7ee51893398908b621d5c2645bc5ba6/src/laminar.cpp#L611). When a new job is to be launched, this function is called for all defined nodes until one of them accepts the job.

One idea I had in mind when implementing it was the ease of adding more hardware. Let's say you have an embedded device you want to run automated tests on. You might create a node for it (with 1 executor), give it a tag like "target-board" and define the device's IP address in the node environment. Then each job that has to run on such hardware would also be assigned that tag, and take the IP address from the environment according to the node it was assigned to. This way, adding a new piece of hardware to allow more jobs in parallel simply means creating a new node and giving it the same tag. I wanted to avoid the configuration nightmare of having to go through every test job and reconfiguring it to run on "target-board1,target-board2".

A further complication is that the tags are also used to filter jobs into groups on the "jobs" page. Not sure if this was a wise choice in retrospect.

**Comment by sbrl** [comment]
Ah, I see. So executors = devices and nodes = cpus?

So each executor tries to see if it can take a run. If multiple executors are able to take the run, the run will get executed by every executor that is able to - resulting in the run getting executed multiple times?

**Comment by ohwgiles** [comment]
Not quite. Nodes is more like devices (target board or server machine). Executors are more like threads, it's just a number used to limit how many jobs can run per node at the same time.

Each **node** tries to see if it can take a run. It can take it if its tags match the job tags **and** the current number of jobs running on that node is less than the defined number of executors for that node. Laminar will stop checking the nodes as soon as one of them "accepts" the job - so no, the run gets executed just once.

**Comment by sbrl** [comment]
Ah, I see. Thanks for being patient with me :-P

I think part of the issue is that it's an abstract concept, and _executors_ and _nodes_ don't have a real-world equivalent - just like save buttons have floppy disks or hard drives on them, and folders look like physical folders. In the same way, the CPUs of virtual machines are sometimes called virtual CPUs.

I guess it's all about the terminology one is familiar with. I'd suggest a system of _agents_ (who execute runs) and groups, but an agent implies a client worker process that runs (potentially) on a different machine.

**Comment by sbrl** [comment]
Perhaps even renaming _nodes_ to _threads_ would help!

**Comment by ohwgiles** [comment]
It would make more sense to rename **executors** to threads - but I don't think that's a good idea because threads do have a specific meaning, and this is not that. However, I do think "agents" is better than "nodes".

Anyway this needs more thought, I think more than a name change is needed.
