### ISSUE TITLE
Suggestion: Make /latest return latest build

### ISSUE THREAD

**Issue by sbrl** [ohwgiles/laminar#82]
If I've got some urls like this:

```
https://ci.example.com/jobs/jobname/17
http://ci.example.com/archive/jobname/17/Archive.tar.7z
```

....it takes me to run #17 for `jobname`. However, if I was to cause a new run to be dispatched, the above url would still lead to run #17 and not, for example, the new run #18.

I propose the following sorts of URLs:

```
https://ci.example.com/jobs/jobname/latest
http://ci.example.com/archive/jobname/latest/Archive.tar.7z
```

By using the `latest` keyword, it would send the user to the latest build of a given type.

In the case of the `/jobs` url, it could be a simple redirect.

In the case of the `/archive` url, it could be a symlink on disk that's maintained by laminar that always points to the latest archive run directory.

**Comment by ohwgiles** [comment]
:+1:

**Comment by sbrl** [comment]
Awesome, thanks!

The next release is going to be awesome :D
