### ISSUE TITLE
development prerequisites on Debian 10

### ISSUE THREAD

**Issue by simevo** [ohwgiles/laminar#83]
while we [wait for the official Debian package](https://bugs.debian.org/919181), here is how to install development prerequisites to build laminar on Debian buster (nextstable):
```
sudo apt install capnproto rapidjson-dev libsqlite-dev libboost-dev cmake make g++ libcapnp-dev
```

**Comment by simevo** [comment]
also needs: `libsqlite3-dev zlib1g-dev`

**Comment by ohwgiles** [comment]
FWIW, I use this script to build the binary packages I release for debian: https://github.com/ohwgiles/laminar/blob/master/docker-build-debian.sh

A little quick and dirty, but gets the job done until the official package gets released

**Comment by ohwgiles** [comment]
Added to `README.md` with e1fe5697d229ff0a224cf88daca519d08aff0382. Closing this issue.
