### ISSUE TITLE
Invalid archive url when config variable not set

### ISSUE THREAD

**Issue by Valicek1** [ohwgiles/laminar#86]
Hi, sorry for bothering you again... I have noticed that path delimiter (`/`) is not added to url when creating artifact link
https://github.com/ohwgiles/laminar/blob/b15166e83b695666f61182ac34cbfefd1762501c/src/laminar.cpp#L207
Which is in contrary to default path `/archive` specified in code... 
https://github.com/ohwgiles/laminar/blob/bb81931ce9324d6d954e3b5ae42c127753a03868/src/laminar.cpp#L59

It could be fixed by adding single `/` to variable definition, but it should be mentioned in docs then. The best solution would be adding simmle if not ends-with-/ then append one / condition  after line 82 in laminar.cpp. 

https://github.com/ohwgiles/laminar/blob/bb81931ce9324d6d954e3b5ae42c127753a03868/src/laminar.cpp#L82-L83

Sorry for just opening issue, but making PR in nam of single slash would be overkill. 

In the end, thanks for your work on laminar, I apreciate it's simplicity (which is balanced by a hell of my bash scripts surrounding it :joy:).

**Comment by ohwgiles** [comment]
Hi again! No problem, just because this is a small issue doesn't make it invalid. And there is no issue too small for a PR ;)

**Comment by ohwgiles** [comment]
Resolved with #87
