### ISSUE TITLE
Badge-URL for cache busting

### ISSUE THREAD

**Issue by transferkraM** [ohwgiles/laminar#89]
Hey guys,

in addition to #50 it would be great to allow additional parameters on the `/badge`-URL for cache busting, e.g. `/badge/project.svg?foo=bar`. Right now any parameter following the `/badge/project.svg` results in 404.

**Comment by ohwgiles** [comment]
I'm not opposed to this, but I'd like to understand why it's necessary. Shouldn't [this](https://github.com/ohwgiles/laminar/blob/95482c78a51ca0940c4c5fbee4e9aef157397b7f/src/server.cpp#L442) be enough? Or is an overzealous reverse-proxy ignoring this?

**Comment by transferkraM** [comment]
Use-case is browser in a dashboard which should automatically refresh badges (which didn't work for us).

**Comment by transferkraM** [comment]
Thank you!
