### ISSUE TITLE
Feature: Display currently running jobs under Jobs link

### ISSUE THREAD

**Issue by palica** [ohwgiles/laminar#9]
Would it be possible to display also running jobs under /jobs?

I could break the display into finished or last job and active jobs

Active Jobs:
hello #10  started ...
__________________________

Last Jobs:
hello #9 Passed
other #3 Failed
...

**Comment by ohwgiles** [comment]
This seems reasonable. I think I would do it without an explicit section break so as not to waste space in the common case where there are no active jobs, in the same way as it appears on the home page. I'll experiment a bit and see how it looks

**Comment by ohwgiles** [comment]
The difficulty I'm having with this is it causes a kind of inconsistent layout. The purpose of the Jobs page is to be able to quickly find a job (by name or tag). With your proposal, the job I'm looking for might be on the top of the page if Laminar is idle, or half-way down the page if it's busy. This means an extra scanning step to find the job I want, and worse, if a new job starts or an active one finishes, the layout will jump, which would be annoying if you were about to click.

I think that's acceptable on the home page, where the point is to get a general overall status, but on the Jobs page I think this would be an overall negative impact on the user experience, so I prefer not to implement it exactly as you describe it.

However, as mentioned in #8, currently the Jobs page doesn't at all reflect whether a job is currently active or not. I should at least display that in the existing row (without layout changes)

**Comment by palica** [comment]
OK, no problem :) I like it with or without this feature.

**Comment by ohwgiles** [comment]
With d3e4db1, the jobs page now updates job rows with their running status

**Comment by palica** [comment]
Oliver, I cannot see running job being listed on the /jobs page.

**Comment by ohwgiles** [comment]
It seems to be working for me:
![laminar-jobs-running](https://user-images.githubusercontent.com/1444499/33482349-3eacb300-d6a1-11e7-86ad-74bc6efb2ca2.png)

**Comment by palica** [comment]
It is again a corner case when it is the first job ever run on the server.

**Comment by ohwgiles** [comment]
Corner case should be now fixed with 2214bef26285dc9
