### ISSUE TITLE
Replace websockets with SSE

### ISSUE THREAD

**Issue by ohwgiles** [ohwgiles/laminar#90]
Server-Side Events are simpler than Websockets and are more than sufficient for laminar's use cases. This can be an opportunity to refactor the HTTP serving code and the JS client API to be simpler and share more.

**Comment by NeoVance** [comment]
Websockets have wider browser support: [97%](https://caniuse.com/#search=websockets) vs the [93%](https://caniuse.com/#search=server-sent events) for server-sent events which would eliminate IE and Opera browser compatibility immediately.

Are you planning on supporting multi-node clusters of laminar in the future?

**Comment by ohwgiles** [comment]
> eliminate IE and Opera browser

Huh? The links you sent show Opera support for SSE as far back as Websockets. I think the only loss would be IE, which I doubt anyone using Laminar would be using.

> Are you planning on supporting multi-node clusters of laminar in the future?

Nope. Laminar should be light enough that its server-side performance wouldn't be the bottleneck anywhere, so I don't think there would be much use for this. That would probably also imply that you have a **lot** of jobs, by which time it's probably worth breaking it up into separate Laminar instances. But what does that have to do with SSE/Websocket?

**Comment by NeoVance** [comment]
> The links you sent show Opera support for SSE as far back as Websockets

*Opera mini* My bad.

> But what does that have to do with SSE/Websocket?

Websockets are better suited if you needed to do some kind of message brokering/routing which might be the case if you planned to scale out executors to multiple nodes. This answer makes the concept of "nodes" even more confusing in the documentation.

**Comment by ohwgiles** [comment]
Currently the sysadmin can use as much executor scale as desired by simply invoking `ssh` or other remote execution mechanism, as described in the documentation. If the load is so high that just managing these remote execution clients means you need to scale the Laminar backend, you are probably doing something wrong.

Laminar currently uses Websockets only to provide status updates from the backend to the frontend. Scaling in this case would only be relevant if you have a lot of users pointing their web browsers at the frontend, which isn't likely given the nature of the tool.

Since these status updates are unidirectional, without any kind of brokering or routing required, Websockets are unnecessarily complex and SSE is a more natural fit. This is particularly noticeable when running Laminar behind a reverse proxy such as nginx: more complex config tweaks are necessary to enable smooth Websocket communication that would be required with SSE.

So despite the slight reduction in browser coverage, I think SSE is a nett win.
