### ISSUE TITLE
Clarify frontend JS API requirements/capabilities

### ISSUE THREAD

**Issue by ohwgiles** [ohwgiles/laminar#91]
New clean JS APIs like [fetch](https://developer.mozilla.org/en/docs/Web/API/Fetch_API) are great but so is browser diversity. Consider making some API compromises to support a wider range of browsers, e.g Firefox ESR, GNOME Web, Konquerer, Midori, surf, netsurf (perhaps unrealistic?)

**Comment by NeoVance** [comment]
Most web developers subscribe to the "progressive enhancement" method. If a feature is not present in the browser you can load additional libraries to provide the required api using the features that are present. There are polyfills which can provide modern APIs even in old browsers for most things. The [whatwg-fetch](https://github.com/github/fetch) polyfill for example to use the fetch api in browsers that don't support it.

**Comment by ohwgiles** [comment]
I think the standard interpretation of progressive enhancement is that the site should be functional (if maybe not as interactive/pretty) without any javascript; layers of javascript can then be added to enhance site functionality. The laminar web frontend is a SPA built on vue so javascript is definitely not going away.

It might just be semantics, but while IMO progressive enhancement doesn't have much to do with polyfills, polyfills are indeed one way to address this issue as described. However, I'm careful to bundle all necessary bits so laminar can be run on a private network, so I'm not too happy with the idea of bundling (probably pretty heavy) stuff that is only to add compatibility with certain browsers. It needs to be weighed up, but there are cases where I'd prefer using an older API than potentially losing support for a certain browser.

**Comment by NeoVance** [comment]
In my own view it extends beyond "I can run javascript so..." I also consider the features available, and try to load the minimum amount of code required to provide the desired functionality with the browser features available.

Software engineers are generally not often running IE8 as their browser of choice, so I don't think you need to worry much about browser compatibility in any case.

**Comment by ohwgiles** [comment]
> I also consider the features available, and try to load the minimum amount of code required to provide the desired functionality with the browser features available.

Exactly, this is an excellent definition. And this issue is about making a considered decision where the Laminar frontend should stand on that scale. A good starting point is probably "Laminar frontend should work anywhere its dependencies (vue, vue-router, chart.js, ansi-up) work", but I haven't had time yet to dig into that to see if it's too restrictive or too permissive.

**Comment by NeoVance** [comment]
Vue claims complete es5 compatibility for all of its libraries including vue-router. [This compatibility table](http://kangax.github.io/compat-table/es5/) shows only a few exceptions for es5 browser compatibility. Those that are incompatible are obsolete browsers, but this list is far from exhaustive.

Chart.js only has the dependency on the canvas API. Chart.js offers support for the following browsers:

- Chrome 50+
- Firefox 45+
- Internet Explorer 11 (Canvas should be available from 9+)
- Edge 14+
- Safari 9+

ansi-up makes no claims of compatibility anywhere I can find, other than a vague statement that it works in the browser and nodejs. This is indeed true. After reading the code I can say that it is 100% es5 compatible.

Most browsers are basing their own internals off of FireFox or WebKit, so I don't think there is going to be a large number of non-standards compliant browsers like there were in the early days, when everyone was building their own browsers from scratch and there were few standards to guide development.

**Comment by ohwgiles** [comment]
Thanks for summarising all that. So it looks like there will be essentially no restrictions imposed by Laminar's dependencies. Laminar already uses a bunch of es6 stuff so it will probably be slightly more restrictive. One thing to keep in mind is that the current Debian Stable only ships Firefox 60. I wanted to use [Streams](https://caniuse.com/#feat=streams) but ended up reverting it in 137f35bdd7c412217af51959d7988e54804c65ea because of this.

**Comment by NeoVance** [comment]
Streams have been implemented in pure JS. S.js might be an option. RXJS is too heavy. It may not be too difficult to write something from scratch either if the use case is simple enough.

**Comment by ohwgiles** [comment]
My preference: don't pull any new dependencies, don't write a streams implementation, just use something not so shiny instead. All Laminar frontend use cases can be trivially dealt with using older JS APIs. If anyone feels like putting in the effort, they can be "upgraded" once a Firefox that supports them lands in Debian Stable.

**Comment by ohwgiles** [comment]
I think this has been sufficiently investigated
