### ISSUE TITLE
Contributor license agreement?

### ISSUE THREAD

**Issue by jakimfett** [ohwgiles/laminar#98]
I'd be interested in seeing some form of contributing document, with expectations and legal boilerplate, both to protect the project and the contributors from down-the-road disagreements.

# Why? 
Because [this](https://www.overclock.net/forum/227-video-game-news/1511277-rddt-wesley-wolfe-issues-dmca-against-bukkit-bukkit-taken-down-4.html) [DMCA](https://www.reddit.com/r/admincraft/comments/2glson/details_on_the_craftbukkit_dmca_takedown_dispute/) [takedown](https://www.planetminecraft.com/blog/the-real-story-behind-the-bukkit-crisis-with-only-real-info/) happened to a codebase I cared rather a lot about, and I'd prefer to avoid a repeat, especially in contexts that would affect non-trivial portions of my build pipeline(s).

---
My contributions, unless noted otherwise, are "as-is" and can be used, copied, modified, or otherwise rejiggered in whatever way the project author and community deems best for the project.  

To the extent of applicable law, I (@jakimfett) disclaims ownership of the bits I wrote, write, or may write in the future, as in my opinion things that can be easily duplicated/copied/etc should be free, open, and collaborative.

**Comment by ohwgiles** [comment]
I'm not familiar with that case, but from a brief overview, I don't think a contributor license agreement is the right tool to protect against such issues. Disclaiming copyright should not be necessary (and in plenty of jurisdictions is not so straightforward). The following off the top of my head:

By contributing, I
- assert that the contributed code is my own work; and
- agree that laminar's license (GPLv3) will apply to this contribution.

Would something like that work for you?
